# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # SensitiveCardOperationsApi
  class SensitiveCardOperationsApi < BaseApi
    # Generate a one-time token used to reveal [prepaid
    # card](page:resources/prepaid-cards) PCI data (card number, CVV, expiry) in
    # the form of image data (base64) or JSON. This is the first step of a
    # two-step client-side flow — the returned token is then passed to [Fetch
    # Card Data]($e/Client%20Side/Fetch%20Card%20Data) using client-side
    # authentication. For a step-by-step guide, see [Display a Virtual
    # Card](page:howtos/display-a-virtual-card).
    # @param [String] destination_token Required parameter: Auto-generated
    # unique identifier representing a transfer destination, including prepaid
    # cards, bank accounts, electronic wallets, and other users, prefixed with
    # `dest-`.
    # @param [String] format Required parameter: Desired format for the prepaid
    # card data.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_card_data_token(destination_token,
                               format)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/prepaid-cards/{destination-token}/show',
                                     Server::API)
                   .template_param(new_parameter(destination_token, key: 'destination-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(format, key: 'format')
                                 .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ShowCardTokenResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('404',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Return [prepaid card](page:resources/prepaid-cards) PCI data (card number,
    # CVV, expiry) in the form of image data, text, or both. This is the second
    # step of a two-step client-side flow — call [Create Card Data
    # Token]($e/Client%20Side/Create%20Card%20Data%20Token) first to obtain the
    # required token, then use client-side authentication to call this endpoint.
    # For a step-by-step guide, see [Display a Virtual
    # Card](page:howtos/display-a-virtual-card).
    # @param [String] destination_token Required parameter: Auto-generated
    # unique identifier representing a transfer destination, including prepaid
    # cards, bank accounts, electronic wallets, and other users, prefixed with
    # `dest-`.
    # @param [ShowCardText | ShowCardImage] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def show_card(destination_token,
                  body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/prepaid-cards/{destination-token}/show',
                                     Server::API)
                   .template_param(new_parameter(destination_token, key: 'destination-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true)
                                .validator(proc do |value|
                                  UnionTypeLookUp.get(:ShowCardRequest)
                                                 .validate(value)
                                end))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(APIHelper.method(:json_serialize))
                   .auth(Single.new('clientside')))
        .response(new_response_handler
                    .deserializer(proc do |response, should_symbolize|
                      APIHelper.deserialize_union_type(
                        UnionTypeLookUp.get(:ShowCardResult),
                        response, should_symbolize, true
                      )
                    end)
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Generate one part of a two-part token required to reveal or set a [prepaid
    # card](page:resources/prepaid-cards) PIN using client-side authentication.
    # The returned token is passed to either [Fetch Card
    # PIN]($e/Client%20Side/Fetch%20Card%20PIN) or [Update Card
    # PIN]($e/Client%20Side/Update%20Card%20PIN). For a step-by-step guide, see
    # [Get or Set a Card PIN](page:howtos/get-or-set-a-card-pin).
    # @param [String] destination_token Required parameter: Auto-generated
    # unique identifier representing a transfer destination, including prepaid
    # cards, bank accounts, electronic wallets, and other users, prefixed with
    # `dest-`.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_card_pin_token(destination_token)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/prepaid-cards/{destination-token}/pin',
                                     Server::API)
                   .template_param(new_parameter(destination_token, key: 'destination-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CardPinTokenResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('404',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Reveal the current PIN for a [prepaid card](page:resources/prepaid-cards).
    # Requires a token from [Create Card PIN
    # Token]($e/Client%20Side/Create%20Card%20PIN%20Token) and uses client-side
    # authentication. For a step-by-step guide, see [Get or Set a Card
    # PIN](page:howtos/get-or-set-a-card-pin).
    # @param [String] destination_token Required parameter: Auto-generated
    # unique identifier representing a transfer destination, including prepaid
    # cards, bank accounts, electronic wallets, and other users, prefixed with
    # `dest-`.
    # @param [GetCardPinRequest] body Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_card_pin(destination_token,
                     body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/prepaid-cards/{destination-token}/pin',
                                     Server::API)
                   .template_param(new_parameter(destination_token, key: 'destination-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('clientside')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CardPinResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Set or change the PIN for a [prepaid card](page:resources/prepaid-cards),
    # if supported by the program. Requires a token from [Create Card PIN
    # Token]($e/Client%20Side/Create%20Card%20PIN%20Token) and uses client-side
    # authentication. For a step-by-step guide, see [Get or Set a Card
    # PIN](page:howtos/get-or-set-a-card-pin).
    # @param [String] destination_token Required parameter: Auto-generated
    # unique identifier representing a transfer destination, including prepaid
    # cards, bank accounts, electronic wallets, and other users, prefixed with
    # `dest-`.
    # @param [SetCardPinRequest] body Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def set_card_pin(destination_token,
                     body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::PUT,
                                     '/prepaid-cards/{destination-token}/pin',
                                     Server::API)
                   .template_param(new_parameter(destination_token, key: 'destination-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('clientside')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CardPinResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end
  end
end
