# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # TransfersApi
  class TransfersApi < BaseApi
    # Create a quote for any supported transfer type in a single unified
    # endpoint. The request body must include a `transferType` property that
    # identifies the type of quote being created: `PAYMENT`, `SPENDBACK`,
    # `RETRACTION`, `TRANSFER`, or `REFUND`.
    # The discriminator on `transferType` determines which request schema is
    # applied and which response type is returned, enabling full polymorphic
    # request and response handling.
    # - **payment**: Equivalent to `POST /payments` — uses the Payment Quote
    # request shape
    # - **spendback**: Equivalent to `POST /spend-back` — uses the Spendback
    # Quote request shape
    # - **retraction**: Equivalent to `POST
    # /payments/{payment-token}/retractions` — uses the Payment Retraction Quote
    # request shape
    # - **transfer**: Equivalent to `POST /transfers` — uses the Transfer Quote
    # request shape
    # - **refund**: Equivalent to `POST /spend-back/{spendback-token}/refunds` —
    # uses the Spendback Refund Quote request shape
    # @param [PortalPaymentQuote | GatewayPaymentQuote | GatewaySpendbackQuote |
    # PortalSpendbackQuote | PaymentRetractionQuote | GatewayTransferQuote |
    # PortalTransferQuote | SpendbackRefundQuote] body Required parameter:
    # Create a universal quote. The request body must include a transferType
    # property to identify the quote type (payment, spendback, retraction,
    # transfer, or refund). The response will be a discriminated union of the
    # corresponding result type based on the transferType.
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def post_transfers(body,
                       accept_language: 'en-US',
                       accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/transfers',
                                     Server::API)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true)
                                .validator(proc do |value|
                                  UnionTypeLookUp.get(:TransferRequest)
                                                 .validate(value)
                                end))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(APIHelper.method(:json_serialize))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(proc do |response, should_symbolize|
                      APIHelper.deserialize_union_type(
                        UnionTypeLookUp.get(:TransferQuoteResult),
                        response, should_symbolize, true
                      )
                    end)
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Fetch the details of a quote by its token. The response shape is
    # determined by the `transferType` discriminator in the response body — a
    # payment quote returns a Payment Result, a spendback returns a Spendback
    # Result, etc.
    # The `transfer-id` path parameter must be a valid transfer token in the
    # format `{prefix}-{uuid}` where prefix is one of `pmnt`, `spnd`, `retx`,
    # `xfer`, or `rfnd`.
    # @param [String] transfer_token Required parameter: The token of the quote
    # to operate on. Must be a valid token for one of the supported quote types:
    # `pmnt-` (payment), `spnd-` (spendback), `retx-` (retraction), `xfer-`
    # (transfer), or `rfnd-` (refund). Tokens use the format `{prefix}-{uuid}`,
    # for example `pmnt-2bbfc967-d12e-4647-a887-d905172fb4bc`.
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_transfer(transfer_token,
                     accept_language: 'en-US',
                     accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/transfers/{transfer-token}',
                                     Server::API)
                   .template_param(new_parameter(transfer_token, key: 'transfer-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(proc do |response, should_symbolize|
                      APIHelper.deserialize_union_type(
                        UnionTypeLookUp.get(:TransferQuoteResult),
                        response, should_symbolize, true
                      )
                    end)
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('404',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Cancel an open transfer quote before it has been accepted. Once cancelled,
    # the quote status transitions to `CANCELLED` and any reserved funds are
    # released.
    # The `transfer-id` path parameter must be a valid transfer token in the
    # format `{prefix}-{uuid}` where prefix is one of `pmnt`, `spnd`, `retx`,
    # `xfer`, or `rfnd`. The response shape is determined by the `transferType`
    # discriminator in the response body.
    # @param [String] transfer_token Required parameter: The token of the quote
    # to operate on. Must be a valid token for one of the supported quote types:
    # `pmnt-` (payment), `spnd-` (spendback), `retx-` (retraction), `xfer-`
    # (transfer), or `rfnd-` (refund). Tokens use the format `{prefix}-{uuid}`,
    # for example `pmnt-2bbfc967-d12e-4647-a887-d905172fb4bc`.
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_transfer(transfer_token,
                        accept_language: 'en-US',
                        accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/transfers/{transfer-token}',
                                     Server::API)
                   .template_param(new_parameter(transfer_token, key: 'transfer-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(proc do |response, should_symbolize|
                      APIHelper.deserialize_union_type(
                        UnionTypeLookUp.get(:TransferQuoteResult),
                        response, should_symbolize, true
                      )
                    end)
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('404',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Accept an open quote to execute the transfer. Once accepted, the quote
    # status transitions from `PENDING_ACCEPTANCE` to `ACCEPTED` and the
    # corresponding transfer is executed.
    # The `transfer-id` path parameter must be a valid transfer token in the
    # format `{prefix}-{uuid}` where prefix is one of `pmnt`, `spnd`, `retx`,
    # `xfer`, or `rfnd`. The response shape is determined by the `transferType`
    # discriminator in the response body.
    # @param [String] transfer_token Required parameter: The token of the quote
    # to operate on. Must be a valid token for one of the supported quote types:
    # `pmnt-` (payment), `spnd-` (spendback), `retx-` (retraction), `xfer-`
    # (transfer), or `rfnd-` (refund). Tokens use the format `{prefix}-{uuid}`,
    # for example `pmnt-2bbfc967-d12e-4647-a887-d905172fb4bc`.
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def post_transfer_accept(transfer_token,
                             accept_language: 'en-US',
                             accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/transfers/{transfer-token}/accept',
                                     Server::API)
                   .template_param(new_parameter(transfer_token, key: 'transfer-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(proc do |response, should_symbolize|
                      APIHelper.deserialize_union_type(
                        UnionTypeLookUp.get(:TransferQuoteResult),
                        response, should_symbolize, true
                      )
                    end)
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Initiate a search for quotes of a specific type. The request body must
    # include a `transferType` property to identify the quote type being
    # searched. The `filters` and `sort` criteria in the body correspond to the
    # selected quote type.
    # Cross-type searches are not supported — each request must target a single
    # quote type. Once the search is created, use the returned `searchId` with
    # `GET /transfers/search/{searchId}` to retrieve paginated results.
    # Supported types and their filter schemas:
    # - **payment** — uses `PaymentSearch`
    # - **spendback** — uses `SpendbackSearch`
    # - **retraction** — uses `PaymentRetractionSearch`
    # - **transfer** — uses `TransferSearch`
    # - **refund** — uses `SpendbackRefundSearch`
    # See [Searching](page:concepts/searching) for the two-step search pattern,
    # [Filtering & Sorting](page:concepts/filtering-sorting) for comparison
    # operators and sort directions, and the [Scope
    # Discriminator](page:concepts/scope-discriminator) for the addressing
    # scheme used in the body.
    # @param [PaymentSearch | SpendbackSearch | PaymentRetractionSearch |
    # TransferSearch | SpendbackRefundSearch] body Required parameter: Search
    # quotes of a specific type. The request body must include transferType to
    # identify which quote type to search. Cross-type searches are not
    # supported. The filters and sort criteria are specific to the quote type
    # identified by transferType.
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def search_transfers(body,
                         accept_language: 'en-US',
                         accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/transfers/search',
                                     Server::API)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true)
                                .validator(proc do |value|
                                  UnionTypeLookUp.get(:TransferSearchRequest)
                                                 .validate(value)
                                end))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(APIHelper.method(:json_serialize))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(proc do |response, should_symbolize|
                      APIHelper.deserialize_union_type(
                        UnionTypeLookUp.get(:TransferSearchResult),
                        response, should_symbolize, true
                      )
                    end)
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Retrieve a specific page of results from a previously initiated quote
    # search. Use the `searchId` returned by `POST /transfers/search` to
    # paginate through results.
    # The response shape is determined by the `transferType` discriminator in
    # the response body. Each item in the `payload` array will be typed
    # according to the quote type of the originating search request.
    # Pagination is controlled by `page` and `pageSize` query parameters
    # (defaults: `page=1`, `pageSize=10`). Cached search results are held for
    # **30 minutes** from creation; an expired `searchId` returns `404 Not
    # Found`. See [Pagination](page:concepts/pagination) and
    # [Searching](page:concepts/searching).
    # @param [UUID | String] search_id Required parameter: Search session
    # identifier returned by the initial POST /search request. Use this value to
    # paginate through search results via the corresponding GET
    # /search/{searchId} endpoint.
    # @param [Integer] page Optional parameter: Page number to retrieve from the
    # cached search results (1-based).
    # @param [Integer] page_size Optional parameter: Number of results per page
    # (1–100).
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def read_transfer_search(search_id,
                             page: 1,
                             page_size: nil,
                             accept_language: 'en-US',
                             accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/transfers/search/{searchId}',
                                     Server::API)
                   .template_param(new_parameter(search_id, key: 'searchId')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(page, key: 'page'))
                   .query_param(new_parameter(page_size, key: 'pageSize'))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(proc do |response, should_symbolize|
                      APIHelper.deserialize_union_type(
                        UnionTypeLookUp.get(:TransferSearchResult),
                        response, should_symbolize, true
                      )
                    end)
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('404',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end
  end
end
