# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # UsersApi
  class UsersApi < BaseApi
    # Create a new [user](page:resources/users) in your
    # [program](page:resources/programs). Once created, the user can be
    # provisioned with [prepaid cards](page:resources/prepaid-cards),
    # bank-account and electronic-wallet
    # [Instruments](page:resources/instruments), and other resources.
    # **Available for API Gateway programs only.** Hosted Portal programs
    # onboard users through [invitations](page:resources/invitations) instead.
    # For a step-by-step guide, see [Onboard
    # Users](page:howtos/onboard-users#path-1-create-a-user-via-api). Check
    # [User Statuses](page:additional-api-information/user-status-types) for
    # possible user states.
    # @param [IndividualUser | BusinessUser] body Required parameter: TODO: type
    # description here
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def post_users(body,
                   accept_language: 'en-US',
                   accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/users',
                                     Server::API)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true)
                                .validator(proc do |value|
                                  UnionTypeLookUp.get(:UserRequest)
                                                 .validate(value)
                                end))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(APIHelper.method(:json_serialize))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UserResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Update a [user](page:resources/users) object (change email, address,
    # personal details, etc.) using a user
    # [token](page:concepts/working-with-tokens). For details on user fields,
    # see [Users](page:resources/users).
    # @param [String] user_token Required parameter: A token representing the
    # user. This must be a `user-` [token](page:concepts/working-with-tokens).
    # For example user-2bbfc967-d12e-4647-a887-d905172fb4bc.
    # @param [IndividualUser | BusinessUser] body Required parameter: TODO: type
    # description here
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def put_users_user_token(user_token,
                             body,
                             accept_language: 'en-US',
                             accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::PUT,
                                     '/users/{user-token}',
                                     Server::API)
                   .template_param(new_parameter(user_token, key: 'user-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true)
                                .validator(proc do |value|
                                  UnionTypeLookUp.get(:UserRequest)
                                                 .validate(value)
                                end))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(APIHelper.method(:json_serialize))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UserResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Fetch a single [user](page:resources/users) record by its `user-`
    # [token](page:concepts/working-with-tokens). Returns the user's personal
    # details, [status](page:additional-api-information/user-status-types), and
    # related [navigation](page:concepts/hateoas) links to associated resources
    # such as [balances](page:resources/balances), [prepaid
    # cards](page:resources/prepaid-cards), and bank-account and
    # electronic-wallet [Instruments](page:resources/instruments).
    # @param [String] user_token Required parameter: A token representing the
    # user. This must be a `user-` [token](page:concepts/working-with-tokens).
    # For example user-2bbfc967-d12e-4647-a887-d905172fb4bc.
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_users_user_token(user_token,
                             accept_language: 'en-US',
                             accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users/{user-token}',
                                     Server::API)
                   .template_param(new_parameter(user_token, key: 'user-token')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UserResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('404',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Search for [users](page:resources/users) using structured filter criteria
    # in the request body. The response carries page 1 of the result set and a
    # `searchId`; use `GET /users/search/{searchId}?page=N&pageSize=N` to read
    # additional pages from the cached result. See
    # [Searching](page:concepts/searching) for the two-step pattern, [Filtering
    # & Sorting](page:concepts/filtering-sorting) for valid operators and sort
    # directions, and the [Scope
    # Discriminator](page:concepts/scope-discriminator) for the addressing
    # scheme.
    # @param [UserSearchRequest] body Required parameter: TODO: type description
    # here
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def search_users(body,
                     accept_language: 'en-US',
                     accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/users/search',
                                     Server::API)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UserListResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end

    # Retrieve a specific page of results from a previous user search request.
    # Pagination via `page` and `pageSize` query parameters (defaults: `page=1`,
    # `pageSize=10`). Cached search results are held for **30 minutes** from
    # creation; an expired `searchId` returns `404 Not Found`. See
    # [Pagination](page:concepts/pagination).
    # @param [UUID | String] search_id Required parameter: Search session
    # identifier returned by the initial POST /search request. Use this value to
    # paginate through search results via the corresponding GET
    # /search/{searchId} endpoint.
    # @param [Integer] page Optional parameter: Page number to retrieve from the
    # cached search results (1-based).
    # @param [Integer] page_size Optional parameter: Number of results per page
    # (1–100).
    # @param [String] accept_language Optional parameter: Header parameter that
    # selects the response language for localized fields (e.g., user-facing
    # event descriptions). Accepts a [BCP
    # 47](https://www.rfc-editor.org/info/bcp47) language tag — see
    # [Localization](page:concepts/localization-parameters) and [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # value list.
    # @param [String] accept_timezone Optional parameter: Header parameter that
    # selects the timezone applied to date/time values in the response. Accepts
    # an IANA timezone identifier — see [Timezone
    # Parameters](page:concepts/timezone-parameters) and [Supported
    # Timezones](page:additional-api-information/supported-timezones) for the
    # value list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def read_user_search(search_id,
                         page: 1,
                         page_size: nil,
                         accept_language: 'en-US',
                         accept_timezone: 'UTC')
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users/search/{searchId}',
                                     Server::API)
                   .template_param(new_parameter(search_id, key: 'searchId')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(page, key: 'page'))
                   .query_param(new_parameter(page_size, key: 'pageSize'))
                   .header_param(new_parameter(accept_language, key: 'Accept-Language'))
                   .header_param(new_parameter(accept_timezone, key: 'Accept-Timezone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('server')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UserListResult.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('403',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('404',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('500',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException)
                    .local_error('default',
                                 'API error response containing error details and status'\
                                  ' information. See [Errors](page:concepts/errors) for the error'\
                                  ' object structure and [Error Types](page:concepts/error-types)'\
                                  ' for common error codes.',
                                 ApiErrorResultException))
        .execute
    end
  end
end
