# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Represents a signature verification failure.
  # @param errors [Array<String>] List of error messages describing why verification failed.
  class SignatureVerificationFailure
    # @return [Array<String>]
    attr_reader :errors

    # Initialize with the list of errors.
    # @param errors [Array<String>] Error messages that caused the failure.
    def initialize(errors)
      @errors = errors
    end

    # Provides a user-friendly string representation of the failure.
    # @return [String]
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} errors: #{@errors}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    # @return [String]
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} errors: #{@errors.inspect}>"
    end
  end
end
