# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Represents a single Http Request.
  class HttpRequest < CoreLibrary::HttpRequest
  end
end
