# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # The `UnionTypeLookUp` class serves as a utility class for
  # storing and managing type combinator templates. It acts as a container for the templates
  # used in handling various oneof/anyof instances within the sdk.
  class UnionTypeLookUp
    include CoreLibrary
    # rubocop:disable Lint/RedundantCopDisableDirective, Style/HashSyntax, Layout/FirstArgumentIndentation
    def self.union_types
      {
        :BalanceSearchResult => OneOf.new(
          [
            LeafType.new(CompanyBalanceListResult, UnionTypeContext.new(
              discriminator_value: 'COMPANY',
              discriminator: 'balanceType'
            )),
            LeafType.new(UserBalanceListResult, UnionTypeContext.new(
              discriminator_value: 'USER',
              discriminator: 'balanceType'
            ))
          ]
        ),

        :PaymentQuote => AnyOf.new(
          [
            LeafType.new(PortalPaymentQuote),
            LeafType.new(GatewayPaymentQuote)
          ]
        ),

        :SpendbackQuote => OneOf.new(
          [
            LeafType.new(GatewaySpendbackQuote),
            LeafType.new(PortalSpendbackQuote)
          ]
        ),

        :TransferQuote => OneOf.new(
          [
            LeafType.new(GatewayTransferQuote),
            LeafType.new(PortalTransferQuote)
          ]
        ),

        :TransferRequest => OneOf.new(
          [
            AnyOf.new(
          [
            LeafType.new(PortalPaymentQuote),
            LeafType.new(GatewayPaymentQuote)
          ]
        ),
            OneOf.new(
          [
            LeafType.new(GatewaySpendbackQuote),
            LeafType.new(PortalSpendbackQuote)
          ]
        ),
            LeafType.new(PaymentRetractionQuote),
            OneOf.new(
          [
            LeafType.new(GatewayTransferQuote),
            LeafType.new(PortalTransferQuote)
          ]
        ),
            LeafType.new(SpendbackRefundQuote)
          ]
        ),

        :TransferQuoteResult => OneOf.new(
          [
            LeafType.new(PaymentResult, UnionTypeContext.new(
              discriminator_value: 'PAYMENT',
              discriminator: 'transferType'
            )),
            LeafType.new(SpendbackResult, UnionTypeContext.new(
              discriminator_value: 'SPENDBACK',
              discriminator: 'transferType'
            )),
            LeafType.new(PaymentRetractionResult, UnionTypeContext.new(
              discriminator_value: 'RETRACTION',
              discriminator: 'transferType'
            )),
            LeafType.new(TransferResult, UnionTypeContext.new(
              discriminator_value: 'TRANSFER',
              discriminator: 'transferType'
            )),
            LeafType.new(SpendbackRefundResult, UnionTypeContext.new(
              discriminator_value: 'REFUND',
              discriminator: 'transferType'
            ))
          ]
        ),

        :TransferSearchRequest => OneOf.new(
          [
            LeafType.new(PaymentSearch),
            LeafType.new(SpendbackSearch),
            LeafType.new(PaymentRetractionSearch),
            LeafType.new(TransferSearch),
            LeafType.new(SpendbackRefundSearch)
          ]
        ),

        :TransferSearchResult => OneOf.new(
          [
            LeafType.new(PaymentListResult, UnionTypeContext.new(
              discriminator_value: 'PAYMENT',
              discriminator: 'transferType'
            )),
            LeafType.new(SpendbackListResult, UnionTypeContext.new(
              discriminator_value: 'SPENDBACK',
              discriminator: 'transferType'
            )),
            LeafType.new(PaymentRetractionListResult, UnionTypeContext.new(
              discriminator_value: 'RETRACTION',
              discriminator: 'transferType'
            )),
            LeafType.new(TransferListResult, UnionTypeContext.new(
              discriminator_value: 'TRANSFER',
              discriminator: 'transferType'
            )),
            LeafType.new(SpendbackRefundListResult, UnionTypeContext.new(
              discriminator_value: 'REFUND',
              discriminator: 'transferType'
            ))
          ]
        ),

        :UserRequest => OneOf.new(
          [
            LeafType.new(IndividualUser, UnionTypeContext.new(
              discriminator_value: 'INDIVIDUAL',
              discriminator: 'userType'
            )),
            LeafType.new(BusinessUser, UnionTypeContext.new(
              discriminator_value: 'BUSINESS',
              discriminator: 'userType'
            ))
          ]
        ),

        :PaymentJobRequest => OneOf.new(
          [
            LeafType.new(GatewayPaymentJob),
            LeafType.new(PortalPaymentJob)
          ]
        ),

        :BankAccount => OneOf.new(
          [
            LeafType.new(UserBankAccount),
            LeafType.new(CompanyBankAccount)
          ]
        ),

        :Ewallet => OneOf.new(
          [
            LeafType.new(UserEwallet),
            LeafType.new(CompanyEwallet)
          ]
        ),

        :InstrumentRequest => OneOf.new(
          [
            OneOf.new(
          [
            LeafType.new(UserBankAccount),
            LeafType.new(CompanyBankAccount)
          ]
        ),
            OneOf.new(
          [
            LeafType.new(UserEwallet),
            LeafType.new(CompanyEwallet)
          ]
        )
          ]
        ),

        :InstrumentResult => OneOf.new(
          [
            LeafType.new(BankAccountResult, UnionTypeContext.new(
              discriminator_value: 'BANK',
              discriminator: 'instrumentType'
            )),
            LeafType.new(EwalletResult, UnionTypeContext.new(
              discriminator_value: 'EWALLET',
              discriminator: 'instrumentType'
            ))
          ]
        ),

        :InstrumentSearchRequest => OneOf.new(
          [
            LeafType.new(BankAccountSearchRequest, UnionTypeContext.new(
              discriminator_value: 'BANK',
              discriminator: 'instrumentType'
            )),
            LeafType.new(EwalletSearchRequest, UnionTypeContext.new(
              discriminator_value: 'EWALLET',
              discriminator: 'instrumentType'
            ))
          ]
        ),

        :IntrumentSearchResult => OneOf.new(
          [
            LeafType.new(BankAccountListResult, UnionTypeContext.new(
              discriminator_value: 'BANK',
              discriminator: 'instrumentType'
            )),
            LeafType.new(EwalletListResult, UnionTypeContext.new(
              discriminator_value: 'EWALLET',
              discriminator: 'instrumentType'
            ))
          ]
        ),

        :InstrumentRequirementSearchRequest => OneOf.new(
          [
            LeafType.new(BankAccountRequirementSearchRequest, UnionTypeContext.new(
              discriminator_value: 'BANK',
              discriminator: 'instrumentType'
            )),
            LeafType.new(EwalletRequirementSearchRequest, UnionTypeContext.new(
              discriminator_value: 'EWALLET',
              discriminator: 'instrumentType'
            ))
          ]
        ),

        :InstrumentRequirementSearchResult => OneOf.new(
          [
            LeafType.new(BankAccountRequirementListResult, UnionTypeContext.new(
              discriminator_value: 'BANK',
              discriminator: 'instrumentType'
            )),
            LeafType.new(EwalletRequirementListResult, UnionTypeContext.new(
              discriminator_value: 'EWALLET',
              discriminator: 'instrumentType'
            ))
          ]
        ),

        :InvitationRequest => OneOf.new(
          [
            LeafType.new(IndividualUserInvitation, UnionTypeContext.new(
              discriminator_value: 'INDIVIDUAL',
              discriminator: 'userType'
            )),
            LeafType.new(BusinessUserInvitation, UnionTypeContext.new(
              discriminator_value: 'BUSINESS',
              discriminator: 'userType'
            ))
          ]
        ),

        :ShowCardRequest => OneOf.new(
          [
            LeafType.new(ShowCardText),
            LeafType.new(ShowCardImage)
          ]
        ),

        :ShowCardResult => OneOf.new(
          [
            LeafType.new(PrepaidCardDataTextResult, UnionTypeContext.new(
              discriminator_value: 'TEXT',
              discriminator: 'format'
            )),
            LeafType.new(PrepaidCardDataImageResult, UnionTypeContext.new(
              discriminator_value: 'IMAGE',
              discriminator: 'format'
            ))
          ]
        ),

        :InvitationJobItem => AnyOf.new(
          [
            LeafType.new(IndividualUserInvitation),
            LeafType.new(BusinessUserInvitation)
          ],
          UnionTypeContext.new(
            is_array: true
          )
        ),

        :WebhookEvents => OneOf.new(
          [
            LeafType.new(BankAccountCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'BANKACCOUNTS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(BankAccountApprovedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'BANKACCOUNTS.UPDATED.STATUS.APPROVED',
              discriminator: 'eventType'
            )),
            LeafType.new(BankAccountDeletedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'BANKACCOUNTS.UPDATED.STATUS.DELETED',
              discriminator: 'eventType'
            )),
            LeafType.new(BankAccountComplianceHoldWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'BANKACCOUNTS.UPDATED.STATUS.COMPLIANCEHOLD',
              discriminator: 'eventType'
            )),
            LeafType.new(BankAccountModifiedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'BANKACCOUNTS.UPDATED.DETAILS.MODIFIED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationJobCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONJOBS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationJobUpdatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONJOBS.UPDATED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationJobCompletedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONJOBS.COMPLETED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationJobFailedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONJOBS.FAILED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationJobCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONJOBS.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentJobCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTJOBS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentJobUpdatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTJOBS.UPDATED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentJobCompletedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTJOBS.COMPLETED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentJobFailedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTJOBS.FAILED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentJobCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTJOBS.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(EwalletCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'ELECTRONICWALLETS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(EwalletApprovedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'ELECTRONICWALLETS.UPDATED.STATUS.APPROVED',
              discriminator: 'eventType'
            )),
            LeafType.new(EwalletDeletedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'ELECTRONICWALLETS.UPDATED.STATUS.DELETED',
              discriminator: 'eventType'
            )),
            LeafType.new(EwalletComplianceHoldWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'ELECTRONICWALLETS.UPDATED.STATUS.COMPLIANCEHOLD',
              discriminator: 'eventType'
            )),
            LeafType.new(EwalletModifiedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'ELECTRONICWALLETS.UPDATED.DETAILS.MODIFIED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONS.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(InvitationUsedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'INVITATIONS.USED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentQuoteCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTQUOTES.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentQuoteAcceptedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTQUOTES.ACCEPTED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentQuoteVoidedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTQUOTES.VOIDED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentQuoteCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTQUOTES.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentRetractionCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTRETRACTIONQUOTES.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentRetractionAcceptedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTRETRACTIONQUOTES.ACCEPTED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentRetractionVoidedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTRETRACTIONQUOTES.VOIDED',
              discriminator: 'eventType'
            )),
            LeafType.new(PaymentRetractionCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PAYMENTRETRACTIONQUOTES.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardPendingOrderWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.PENDINGORDER',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardPendingReleaseWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.PENDINGRELEASE',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardPendingActivationWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.PENDINGACTIVATION',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardActiveWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.ACTIVE',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardSuspendedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.SUSPENDED',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardComplianceHoldWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.COMPLIANCEHOLD',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardClosedLostWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDLOST',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardClosedExpiredWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDEXPIRED',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardClosedFraudWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDFRAUD',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardClosedStolenWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDSTOLEN',
              discriminator: 'eventType'
            )),
            LeafType.new(PrepaidCardClosedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'PREPAIDCARDS.UPDATED.STATUS.CLOSED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptPendingWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.PENDING',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptCompletedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.COMPLETED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptFailedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.FAILED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptScheduledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.SCHEDULED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptProcessingWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.PROCESSING',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptReversedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.REVERSED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptRefundedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.REFUNDED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptReturnedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.STATUS.RETURNED',
              discriminator: 'eventType'
            )),
            LeafType.new(ReceiptModifiedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'RECEIPTS.UPDATED.DETAILS.MODIFIED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKQUOTES.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackAcceptedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKQUOTES.ACCEPTED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackVoidedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKQUOTES.VOIDED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKQUOTES.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackRefundCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKREFUNDQUOTES.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackRefundAcceptedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKREFUNDQUOTES.ACCEPTED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackRefundVoidedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKREFUNDQUOTES.VOIDED',
              discriminator: 'eventType'
            )),
            LeafType.new(SpendbackRefundCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'SPENDBACKREFUNDQUOTES.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(TransferQuoteCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'TRANSFERQUOTES.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(TransferQuoteAcceptedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'TRANSFERQUOTES.ACCEPTED',
              discriminator: 'eventType'
            )),
            LeafType.new(TransferQuoteVoidedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'TRANSFERQUOTES.VOIDED',
              discriminator: 'eventType'
            )),
            LeafType.new(TransferQuoteCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'TRANSFERQUOTES.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserEventStartedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USEREVENTS.STARTED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserEventUpdatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USEREVENTS.UPDATED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserEventCompletedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USEREVENTS.COMPLETED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserEventCancelledWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USEREVENTS.CANCELLED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserCreatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.CREATED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserRegistrationInProgressWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.STATUS.REGISTRATIONINPROGRESS',
              discriminator: 'eventType'
            )),
            LeafType.new(UserRegistrationCompleteWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE',
              discriminator: 'eventType'
            )),
            LeafType.new(UserKycRequiredWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.KYC.REQUIRED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserKycProvidedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.KYC.PROVIDED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserKycRejectedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.KYC.REJECTED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserKycApprovedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.KYC.APPROVED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserIdvPassedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.IDV.PASSED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserIdvFailedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.IDV.FAILED',
              discriminator: 'eventType'
            )),
            LeafType.new(UserDetailsUpdatedWebhookRequest, UnionTypeContext.new(
              discriminator_value: 'USERS.UPDATED.DETAILS',
              discriminator: 'eventType'
            ))
          ]
        )
      }
    end
    # rubocop:enable Lint/RedundantCopDisableDirective, Style/HashSyntax, Layout/FirstArgumentIndentation

    def self.get(name)
      UnionTypeLookUp.union_types[name]
    end
  end
end
