# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  #  pq_api_v2 client class.
  class Client
    include CoreLibrary
    attr_reader :config, :auth_managers

    def user_agent_detail
      config.user_agent_detail
    end

    # Returns the configured authentication server instance.
    def server
      @auth_managers['server']
    end

    # Access to accounts controller.
    # @return [AccountsApi] Returns the controller instance.
    def accounts
      @accounts ||= AccountsApi.new @global_configuration
    end

    # Access to agreements controller.
    # @return [AgreementsApi] Returns the controller instance.
    def agreements
      @agreements ||= AgreementsApi.new @global_configuration
    end

    # Access to balances controller.
    # @return [BalancesApi] Returns the controller instance.
    def balances
      @balances ||= BalancesApi.new @global_configuration
    end

    # Access to compliance controller.
    # @return [ComplianceApi] Returns the controller instance.
    def compliance
      @compliance ||= ComplianceApi.new @global_configuration
    end

    # Access to documents controller.
    # @return [DocumentsApi] Returns the controller instance.
    def documents
      @documents ||= DocumentsApi.new @global_configuration
    end

    # Access to user_events controller.
    # @return [UserEventsApi] Returns the controller instance.
    def user_events
      @user_events ||= UserEventsApi.new @global_configuration
    end

    # Access to transfers controller.
    # @return [TransfersApi] Returns the controller instance.
    def transfers
      @transfers ||= TransfersApi.new @global_configuration
    end

    # Access to prepaid_cards controller.
    # @return [PrepaidCardsApi] Returns the controller instance.
    def prepaid_cards
      @prepaid_cards ||= PrepaidCardsApi.new @global_configuration
    end

    # Access to programs controller.
    # @return [ProgramsApi] Returns the controller instance.
    def programs
      @programs ||= ProgramsApi.new @global_configuration
    end

    # Access to receipts controller.
    # @return [ReceiptsApi] Returns the controller instance.
    def receipts
      @receipts ||= ReceiptsApi.new @global_configuration
    end

    # Access to statements controller.
    # @return [StatementsApi] Returns the controller instance.
    def statements
      @statements ||= StatementsApi.new @global_configuration
    end

    # Access to users controller.
    # @return [UsersApi] Returns the controller instance.
    def users
      @users ||= UsersApi.new @global_configuration
    end

    # Access to webhooks_subscriptions controller.
    # @return [WebhooksSubscriptionsApi] Returns the controller instance.
    def webhooks_subscriptions
      @webhooks_subscriptions ||= WebhooksSubscriptionsApi.new @global_configuration
    end

    # Access to jobs controller.
    # @return [JobsApi] Returns the controller instance.
    def jobs
      @jobs ||= JobsApi.new @global_configuration
    end

    # Access to authorizations controller.
    # @return [AuthorizationsApi] Returns the controller instance.
    def authorizations
      @authorizations ||= AuthorizationsApi.new @global_configuration
    end

    # Access to instruments controller.
    # @return [InstrumentsApi] Returns the controller instance.
    def instruments
      @instruments ||= InstrumentsApi.new @global_configuration
    end

    # Access to invitations controller.
    # @return [InvitationsApi] Returns the controller instance.
    def invitations
      @invitations ||= InvitationsApi.new @global_configuration
    end

    # Access to sensitive_card_operations controller.
    # @return [SensitiveCardOperationsApi] Returns the controller instance.
    def sensitive_card_operations
      @sensitive_card_operations ||= SensitiveCardOperationsApi.new @global_configuration
    end

    # Access to oauth_authorization controller.
    # @return [OauthAuthorizationApi] Returns the controller instance.
    def oauth_authorization
      @oauth_authorization ||= OauthAuthorizationApi.new @global_configuration
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 30,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524, 408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put get put], http_callback: nil,
      proxy_settings: nil, logging_configuration: nil,
      environment: Environment::SANDBOX,
      sandbox_instance: SandboxInstance::SANDBOX,
      uat_instance: UatInstance::UAT1, server_credentials: nil,
      clientside_credentials: nil, api_version: '2026.02.01', config: nil
    )
      @config = if config.nil?
                  Configuration.new(
                    connection: connection, adapter: adapter, timeout: timeout,
                    max_retries: max_retries, retry_interval: retry_interval,
                    backoff_factor: backoff_factor,
                    retry_statuses: retry_statuses,
                    retry_methods: retry_methods, http_callback: http_callback,
                    proxy_settings: proxy_settings,
                    logging_configuration: logging_configuration,
                    environment: environment,
                    sandbox_instance: sandbox_instance,
                    uat_instance: uat_instance,
                    server_credentials: server_credentials,
                    clientside_credentials: clientside_credentials,
                    api_version: api_version
                  )
                else
                  config
                end
      user_agent_params = BaseApi.user_agent_parameters

      @global_configuration = GlobalConfiguration.new(client_configuration: @config)
                                                 .base_uri_executor(@config.method(:get_base_uri))
                                                 .global_errors(BaseApi::GLOBAL_ERRORS)
                                                 .user_agent(BaseApi.user_agent,
                                                             agent_parameters: user_agent_params)
                                                 .global_header('API-Version', @config.api_version)

      initialize_auth_managers(@global_configuration)
      @global_configuration = @global_configuration.auth_managers(@auth_managers)
    end

    # Initializes the auth managers hash used for authenticating API calls.
    # @param [GlobalConfiguration] global_config The global configuration of the SDK)
    def initialize_auth_managers(global_config)
      @auth_managers = {}
      http_client_config = global_config.client_configuration
      %w[server clientside].each { |auth| @auth_managers[auth] = nil }
      @auth_managers['server'] = Server.new(http_client_config.server_credentials, global_config)
      @auth_managers['clientside'] = Clientside.new(http_client_config.clientside_credentials)
    end

    # Creates a client directly from environment variables.
    def self.from_env(**overrides)
      default_config = Configuration.build_default_config_from_env
      new_config = default_config.clone_with(**overrides)
      new(config: new_config)
    end
  end
end
