# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # A structured address with a type classifier.
  class AddressObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Classifies the address kind on a [User](page:resources/users) profile —
    # `RESIDENTIAL` (where the payee lives, used for KYC), `MAILING` (where
    # physical mail and plastic cards are sent), or `BUSINESS` (the registered
    # address of a business-type user). Most user records carry a residential
    # address and may add mailing or business addresses as needed.
    # @return [String]
    attr_accessor :address_type

    # Address Line 1
    # @return [String]
    attr_accessor :address_line1

    # Second line of the street address
    # @return [String]
    attr_accessor :address_line2

    # Third line of the street address
    # @return [String]
    attr_accessor :address_line3

    # City name with a maximum length of 50 characters
    # @return [String]
    attr_accessor :city

    # State, province, or region
    # @return [String]
    attr_accessor :region

    # Postal or ZIP code
    # @return [String]
    attr_accessor :postal_code

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :country

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['address_type'] = 'addressType'
      @_hash['address_line1'] = 'addressLine1'
      @_hash['address_line2'] = 'addressLine2'
      @_hash['address_line3'] = 'addressLine3'
      @_hash['city'] = 'city'
      @_hash['region'] = 'region'
      @_hash['postal_code'] = 'postalCode'
      @_hash['country'] = 'country'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        address_line2
        address_line3
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(address_type:, address_line1:, city:, region:, postal_code:,
                   country:, address_line2: SKIP, address_line3: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @address_type = address_type
      @address_line1 = address_line1
      @address_line2 = address_line2 unless address_line2 == SKIP
      @address_line3 = address_line3 unless address_line3 == SKIP
      @city = city
      @region = region
      @postal_code = postal_code
      @country = country
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      address_type = hash.key?('addressType') ? hash['addressType'] : nil
      address_line1 = hash.key?('addressLine1') ? hash['addressLine1'] : nil
      city = hash.key?('city') ? hash['city'] : nil
      region = hash.key?('region') ? hash['region'] : nil
      postal_code = hash.key?('postalCode') ? hash['postalCode'] : nil
      country = hash.key?('country') ? hash['country'] : nil
      address_line2 = hash.key?('addressLine2') ? hash['addressLine2'] : SKIP
      address_line3 = hash.key?('addressLine3') ? hash['addressLine3'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      AddressObject.new(address_type: address_type,
                        address_line1: address_line1,
                        city: city,
                        region: region,
                        postal_code: postal_code,
                        country: country,
                        address_line2: address_line2,
                        address_line3: address_line3,
                        additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [AddressObject | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.address_type,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.address_line1,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.city,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.region,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.postal_code,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.country,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['addressType'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['addressLine1'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['city'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['region'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['postalCode'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['country'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} address_type: #{@address_type}, address_line1: #{@address_line1},"\
      " address_line2: #{@address_line2}, address_line3: #{@address_line3}, city: #{@city},"\
      " region: #{@region}, postal_code: #{@postal_code}, country: #{@country},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} address_type: #{@address_type.inspect}, address_line1:"\
      " #{@address_line1.inspect}, address_line2: #{@address_line2.inspect}, address_line3:"\
      " #{@address_line3.inspect}, city: #{@city.inspect}, region: #{@region.inspect},"\
      " postal_code: #{@postal_code.inspect}, country: #{@country.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
