# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Account-level [Balance](page:resources/balances) — amount and currency of
  # available funds. The polymorphic `balanceType` discriminator selects between
  # `CompanyBalanceObject` (program funding) and `UserBalanceObject`
  # (per-payee). See [Balances](page:resources/balances).
  class BalanceBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Amount of money in the account, represented as a string to preserve
    # decimal precision ([learn more](page:concepts/monetary-precision))
    # @return [String]
    attr_accessor :amount

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # Combination of the amount and currency type. On transfer-quote responses
    # this string is **always sign-free** (never contains `-`, `(`, or `)`) — it
    # can be rendered directly without further sign-stripping. ([learn
    # more](page:concepts/monetary-precision#quote-responses-are-always-non-nega
    # tive))
    # @return [String]
    attr_accessor :formatted_amount

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :token

    # Discriminator on a balance object. `COMPANY` selects a
    # `CompanyBalanceObject`; `USER` selects a `UserBalanceObject`. See [Balance
    # Type](page:resources/balances) for the discriminator semantics.
    # @return [String]
    attr_accessor :balance_type

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :program_token

    # Program-assigned identifier for the user. Used by Hosted Portal programs
    # (with `email`) to address payees in transactional and search bodies. See
    # [Scope Discriminator](page:concepts/scope-discriminator).
    # @return [String]
    attr_accessor :program_user_id

    # Auto-generated unique identifier representing a dest, prefixed with dest-.
    # @return [String]
    attr_accessor :prepaid_card_token

    # Array of prepaid cards related to this balance, only populated if the
    # balance is shared between multiple cards (e.g. physical, instant,
    # ApplePay, GooglePay, etc.)
    # @return [Array[String]]
    attr_accessor :related_cards

    # Capabilities the platform will allow this balance to be used for — for
    # example, `PAYMENT_SOURCE` if the balance can fund outbound payments,
    # `PREPAID_CARD` if it is a prepaid-card balance. See [Balance
    # Capabilities](page:resources/balances) for the value list.
    # @return [Array[String]]
    attr_accessor :capabilities

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount'] = 'amount'
      @_hash['currency'] = 'currency'
      @_hash['formatted_amount'] = 'formattedAmount'
      @_hash['token'] = 'token'
      @_hash['balance_type'] = 'balanceType'
      @_hash['program_token'] = 'programToken'
      @_hash['program_user_id'] = 'programUserId'
      @_hash['prepaid_card_token'] = 'prepaidCardToken'
      @_hash['related_cards'] = 'relatedCards'
      @_hash['capabilities'] = 'capabilities'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        program_user_id
        prepaid_card_token
        related_cards
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(amount: '0', currency: 'USD', formatted_amount: '$0.05 USD',
                   token:, balance_type:, program_token:, capabilities:,
                   program_user_id: SKIP, prepaid_card_token: SKIP,
                   related_cards: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @amount = amount
      @currency = currency
      @formatted_amount = formatted_amount
      @token = token
      @balance_type = balance_type
      @program_token = program_token
      @program_user_id = program_user_id unless program_user_id == SKIP
      @prepaid_card_token = prepaid_card_token unless prepaid_card_token == SKIP
      @related_cards = related_cards unless related_cards == SKIP
      @capabilities = capabilities
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = hash['amount'] ||= '0'
      currency = hash['currency'] ||= 'USD'
      formatted_amount = hash['formattedAmount'] ||= '$0.05 USD'
      token = hash.key?('token') ? hash['token'] : nil
      balance_type = hash.key?('balanceType') ? hash['balanceType'] : nil
      program_token = hash.key?('programToken') ? hash['programToken'] : nil
      capabilities = hash.key?('capabilities') ? hash['capabilities'] : nil
      program_user_id =
        hash.key?('programUserId') ? hash['programUserId'] : SKIP
      prepaid_card_token =
        hash.key?('prepaidCardToken') ? hash['prepaidCardToken'] : SKIP
      related_cards = hash.key?('relatedCards') ? hash['relatedCards'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      BalanceBase.new(amount: amount,
                      currency: currency,
                      formatted_amount: formatted_amount,
                      token: token,
                      balance_type: balance_type,
                      program_token: program_token,
                      capabilities: capabilities,
                      program_user_id: program_user_id,
                      prepaid_card_token: prepaid_card_token,
                      related_cards: related_cards,
                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount}, currency: #{@currency}, formatted_amount:"\
      " #{@formatted_amount}, token: #{@token}, balance_type: #{@balance_type}, program_token:"\
      " #{@program_token}, program_user_id: #{@program_user_id}, prepaid_card_token:"\
      " #{@prepaid_card_token}, related_cards: #{@related_cards}, capabilities: #{@capabilities},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount.inspect}, currency: #{@currency.inspect},"\
      " formatted_amount: #{@formatted_amount.inspect}, token: #{@token.inspect}, balance_type:"\
      " #{@balance_type.inspect}, program_token: #{@program_token.inspect}, program_user_id:"\
      " #{@program_user_id.inspect}, prepaid_card_token: #{@prepaid_card_token.inspect},"\
      " related_cards: #{@related_cards.inspect}, capabilities: #{@capabilities.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
