# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Discriminator value identifying this as a company balance list result.
  class BalanceType2
    BALANCE_TYPE2 = [
      # TODO: Write general description for COMPANY
      COMPANY = 'COMPANY'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      BALANCE_TYPE2.include?(value)
    end

    def self.from_value(value, default_value = COMPANY)
      return default_value if value.nil?

      default_value
    end
  end
end
