# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Discriminator on a balance object. `COMPANY` selects a
  # `CompanyBalanceObject`; `USER` selects a `UserBalanceObject`. See [Balance
  # Type](page:resources/balances) for the discriminator semantics.
  class BalanceType1
    BALANCE_TYPE1 = [
      # TODO: Write general description for USER
      USER = 'USER'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      BALANCE_TYPE1.include?(value)
    end

    def self.from_value(value, default_value = USER)
      return default_value if value.nil?

      default_value
    end
  end
end
