# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Classifies the bank-account information required for a given (country,
  # currency) combination.
  class BankAccountRequirement < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :country

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # Fee configuration including category and distribution details. All
    # monetary fields within this object (`totalAmount`, `transactionAmount`,
    # `valueAmount`, and the `amount` on each distribution entry) are **always
    # non-negative** on responses. ([learn
    # more](page:concepts/monetary-precision#quote-responses-are-always-non-nega
    # tive))
    # @return [FeeConfiguration]
    attr_accessor :fee

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :source_country

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :source_currency

    # Supported transfer method types for this requirement
    # @return [Array[String]]
    attr_accessor :methods

    # Array of required fields for the bank account
    # @return [Array[BankAccountRequiredFields]]
    attr_accessor :requirements

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['country'] = 'country'
      @_hash['currency'] = 'currency'
      @_hash['fee'] = 'fee'
      @_hash['source_country'] = 'sourceCountry'
      @_hash['source_currency'] = 'sourceCurrency'
      @_hash['methods'] = 'methods'
      @_hash['requirements'] = 'requirements'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        country
        currency
        fee
        source_country
        source_currency
        methods
        requirements
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(country: SKIP, currency: 'USD', fee: SKIP,
                   source_country: SKIP, source_currency: 'USD', methods: SKIP,
                   requirements: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @country = country unless country == SKIP
      @currency = currency unless currency == SKIP
      @fee = fee unless fee == SKIP
      @source_country = source_country unless source_country == SKIP
      @source_currency = source_currency unless source_currency == SKIP
      @methods = methods unless methods == SKIP
      @requirements = requirements unless requirements == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      country = hash.key?('country') ? hash['country'] : SKIP
      currency = hash['currency'] ||= 'USD'
      fee = FeeConfiguration.from_hash(hash['fee']) if hash['fee']
      source_country = hash.key?('sourceCountry') ? hash['sourceCountry'] : SKIP
      source_currency = hash['sourceCurrency'] ||= 'USD'
      methods = hash.key?('methods') ? hash['methods'] : SKIP
      # Parameter is an array, so we need to iterate through it
      requirements = nil
      unless hash['requirements'].nil?
        requirements = []
        hash['requirements'].each do |structure|
          requirements << (BankAccountRequiredFields.from_hash(structure) if structure)
        end
      end

      requirements = SKIP unless hash.key?('requirements')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      BankAccountRequirement.new(country: country,
                                 currency: currency,
                                 fee: fee,
                                 source_country: source_country,
                                 source_currency: source_currency,
                                 methods: methods,
                                 requirements: requirements,
                                 additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [BankAccountRequirement | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} country: #{@country}, currency: #{@currency}, fee: #{@fee}, source_country:"\
      " #{@source_country}, source_currency: #{@source_currency}, methods: #{@methods},"\
      " requirements: #{@requirements}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} country: #{@country.inspect}, currency: #{@currency.inspect}, fee:"\
      " #{@fee.inspect}, source_country: #{@source_country.inspect}, source_currency:"\
      " #{@source_currency.inspect}, methods: #{@methods.inspect}, requirements:"\
      " #{@requirements.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
