# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module PqApiV2
  # Bank-account [Instrument](page:resources/instruments) — a payout destination
  # representing a payee's or company's bank account in a specific country and
  # currency. Carries the country, currency, ownership purpose (`PERSONAL` /
  # `BUSINESS`), the rail-specific identifying fields (routing number, account
  # number, IBAN, etc.), and a verification status that progresses from creation
  # through platform validation. The unified Instruments resource discriminates
  # bank accounts vs electronic wallets via `instrumentType: BANK`.
  class BankAccountBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token identifying the destination of funds — a bank-account or
    # electronic-wallet [Instrument](page:resources/instruments), or a [Prepaid
    # Card](page:resources/prepaid-cards). Prefix `dest-`.
    # @return [String]
    attr_accessor :token

    # Discriminator value identifying this as a bank account instrument.
    # @return [InstrumentType]
    attr_accessor :instrument_type

    # Ownership category of a bank-account
    # [Instrument](page:resources/instruments) — `PERSONAL` (held by an
    # individual payee) or `BUSINESS` (held by an entity). Determines applicable
    # KYC and reporting rules. See [Bank Account
    # Types](page:additional-api-information/bank-account-types) for the value
    # list.
    # @return [String]
    attr_accessor :purpose

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :country

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # Address information for the bank account
    # @return [BankAccountAddress]
    attr_accessor :address

    # Date and time when the resource was created. ISO 8601 format.
    # @return [DateTime]
    attr_accessor :created_at

    # User-supplied description of the bank account for reference
    # @return [String]
    attr_accessor :description

    # Array of bank account fields and values
    # @return [Array[BankAccountField]]
    attr_accessor :fields

    # Current verification status of a bank-account
    # [Instrument](page:resources/instruments) — for example, the account is
    # awaiting validation, has been approved, or is under compliance hold. See
    # [Bank Account Types](page:additional-api-information/bank-account-types)
    # for the value list.
    # @return [String]
    attr_accessor :status

    # Financial purpose of a bank-account
    # [Instrument](page:resources/instruments) — for example, `CHECKING`,
    # `SAVINGS`. See [Bank Account
    # Types](page:additional-api-information/bank-account-types) for the full
    # list.
    # @return [String]
    attr_accessor :type

    # Underlying rail used to settle a `transferType: TRANSFER` to a
    # bank-account or electronic-wallet
    # [Instrument](page:resources/instruments). Examples: `IACH` (international
    # ACH), `WIRE`, `LOCAL`. Available methods depend on the destination's
    # country and currency — discover them via `POST
    # /instruments/requirements/search`. See [Transfer Method
    # Types](page:additional-api-information/transfer-method-types) for the full
    # list.
    # @return [String]
    attr_accessor :method

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['instrument_type'] = 'instrumentType'
      @_hash['purpose'] = 'purpose'
      @_hash['country'] = 'country'
      @_hash['currency'] = 'currency'
      @_hash['address'] = 'address'
      @_hash['created_at'] = 'createdAt'
      @_hash['description'] = 'description'
      @_hash['fields'] = 'fields'
      @_hash['status'] = 'status'
      @_hash['type'] = 'type'
      @_hash['method'] = 'method'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        address
        description
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(token:, instrument_type: InstrumentType::BANK, purpose:,
                   country:, currency:, created_at:, fields:, status:, type:,
                   method:, address: SKIP, description: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @token = token
      @instrument_type = instrument_type
      @purpose = purpose
      @country = country
      @currency = currency
      @address = address unless address == SKIP
      @created_at = created_at
      @description = description unless description == SKIP
      @fields = fields
      @status = status
      @type = type
      @method = method
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : nil
      instrument_type = hash['instrumentType'] ||= InstrumentType::BANK
      purpose = hash.key?('purpose') ? hash['purpose'] : nil
      country = hash.key?('country') ? hash['country'] : nil
      currency = hash.key?('currency') ? hash['currency'] : nil
      created_at = if hash.key?('createdAt')
                     (DateTimeHelper.from_rfc3339(hash['createdAt']) if hash['createdAt'])
                   end
      # Parameter is an array, so we need to iterate through it
      fields = nil
      unless hash['fields'].nil?
        fields = []
        hash['fields'].each do |structure|
          fields << (BankAccountField.from_hash(structure) if structure)
        end
      end

      fields = nil unless hash.key?('fields')
      status = hash.key?('status') ? hash['status'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      method = hash.key?('method') ? hash['method'] : nil
      address = BankAccountAddress.from_hash(hash['address']) if hash['address']
      description = hash.key?('description') ? hash['description'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      BankAccountBase.new(token: token,
                          instrument_type: instrument_type,
                          purpose: purpose,
                          country: country,
                          currency: currency,
                          created_at: created_at,
                          fields: fields,
                          status: status,
                          type: type,
                          method: method,
                          address: address,
                          description: description,
                          additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    # Validates an instance of the object from a given value.
    # @param [BankAccountBase | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.token,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.instrument_type,
                                  ->(val) { InstrumentType.validate(val) }) and
            APIHelper.valid_type?(value.purpose,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.country,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.currency,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.created_at,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.fields,
                                  ->(val) { BankAccountField.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.status,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.type,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.method,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['token'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['instrumentType'],
                                ->(val) { InstrumentType.validate(val) }) and
          APIHelper.valid_type?(value['purpose'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['country'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['currency'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['createdAt'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['fields'],
                                ->(val) { BankAccountField.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['status'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['type'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['method'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, instrument_type: #{@instrument_type}, purpose:"\
      " #{@purpose}, country: #{@country}, currency: #{@currency}, address: #{@address},"\
      " created_at: #{@created_at}, description: #{@description}, fields: #{@fields}, status:"\
      " #{@status}, type: #{@type}, method: #{@method}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, instrument_type: #{@instrument_type.inspect},"\
      " purpose: #{@purpose.inspect}, country: #{@country.inspect}, currency:"\
      " #{@currency.inspect}, address: #{@address.inspect}, created_at: #{@created_at.inspect},"\
      " description: #{@description.inspect}, fields: #{@fields.inspect}, status:"\
      " #{@status.inspect}, type: #{@type.inspect}, method: #{@method.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
