# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Create or update a bank-account [Instrument](page:resources/instruments) on
  # a program account (the `instrumentType` discriminator must be `BANK`). The
  # required fields vary by country and currency — discover them via `POST
  # /instruments/requirements/search`. See [Bank Account Field
  # Types](page:additional-api-information/bank-account-field-types) and [Bank
  # Account Types](page:additional-api-information/bank-account-types).
  class CompanyBankAccount < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Discriminator value identifying this as a bank account instrument.
    # @return [InstrumentType]
    attr_accessor :instrument_type

    # Account token identifying the target account.
    # @return [String]
    attr_accessor :account_token

    # Ownership category of a bank-account
    # [Instrument](page:resources/instruments) — `PERSONAL` (held by an
    # individual payee) or `BUSINESS` (held by an entity). Determines applicable
    # KYC and reporting rules. See [Bank Account
    # Types](page:additional-api-information/bank-account-types) for the value
    # list.
    # @return [String]
    attr_accessor :purpose

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :country

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # User-supplied description of the bank account for reference
    # @return [String]
    attr_accessor :description

    # Required bank account fields as determined by requirements
    # @return [Array[BankAccountField]]
    attr_accessor :fields

    # Financial purpose of a bank-account
    # [Instrument](page:resources/instruments) — for example, `CHECKING`,
    # `SAVINGS`. See [Bank Account
    # Types](page:additional-api-information/bank-account-types) for the full
    # list.
    # @return [String]
    attr_accessor :type

    # Underlying rail used to settle a `transferType: TRANSFER` to a
    # bank-account or electronic-wallet
    # [Instrument](page:resources/instruments). Examples: `IACH` (international
    # ACH), `WIRE`, `LOCAL`. Available methods depend on the destination's
    # country and currency — discover them via `POST
    # /instruments/requirements/search`. See [Transfer Method
    # Types](page:additional-api-information/transfer-method-types) for the full
    # list.
    # @return [String]
    attr_accessor :method

    # Address information for the bank account
    # @return [BankAccountAddress]
    attr_accessor :address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['instrument_type'] = 'instrumentType'
      @_hash['account_token'] = 'accountToken'
      @_hash['purpose'] = 'purpose'
      @_hash['country'] = 'country'
      @_hash['currency'] = 'currency'
      @_hash['description'] = 'description'
      @_hash['fields'] = 'fields'
      @_hash['type'] = 'type'
      @_hash['method'] = 'method'
      @_hash['address'] = 'address'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        address
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(instrument_type: InstrumentType::BANK, account_token:,
                   purpose:, country:, currency: 'USD', description:, fields:,
                   type:, method:, address: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @instrument_type = instrument_type
      @account_token = account_token
      @purpose = purpose
      @country = country
      @currency = currency
      @description = description
      @fields = fields
      @type = type
      @method = method
      @address = address unless address == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      instrument_type = hash['instrumentType'] ||= InstrumentType::BANK
      account_token = hash.key?('accountToken') ? hash['accountToken'] : nil
      purpose = hash.key?('purpose') ? hash['purpose'] : nil
      country = hash.key?('country') ? hash['country'] : nil
      currency = hash['currency'] ||= 'USD'
      description = hash.key?('description') ? hash['description'] : nil
      # Parameter is an array, so we need to iterate through it
      fields = nil
      unless hash['fields'].nil?
        fields = []
        hash['fields'].each do |structure|
          fields << (BankAccountField.from_hash(structure) if structure)
        end
      end

      fields = nil unless hash.key?('fields')
      type = hash.key?('type') ? hash['type'] : nil
      method = hash.key?('method') ? hash['method'] : nil
      address = BankAccountAddress.from_hash(hash['address']) if hash['address']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      CompanyBankAccount.new(instrument_type: instrument_type,
                             account_token: account_token,
                             purpose: purpose,
                             country: country,
                             currency: currency,
                             description: description,
                             fields: fields,
                             type: type,
                             method: method,
                             address: address,
                             additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [CompanyBankAccount | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.instrument_type,
                                ->(val) { InstrumentType.validate(val) }) and
            APIHelper.valid_type?(value.account_token,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.purpose,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.country,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.currency,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.description,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.fields,
                                  ->(val) { BankAccountField.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.type,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.method,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['instrumentType'],
                              ->(val) { InstrumentType.validate(val) }) and
          APIHelper.valid_type?(value['accountToken'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['purpose'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['country'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['currency'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['description'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['fields'],
                                ->(val) { BankAccountField.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['type'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['method'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} instrument_type: #{@instrument_type}, account_token: #{@account_token},"\
      " purpose: #{@purpose}, country: #{@country}, currency: #{@currency}, description:"\
      " #{@description}, fields: #{@fields}, type: #{@type}, method: #{@method}, address:"\
      " #{@address}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} instrument_type: #{@instrument_type.inspect}, account_token:"\
      " #{@account_token.inspect}, purpose: #{@purpose.inspect}, country: #{@country.inspect},"\
      " currency: #{@currency.inspect}, description: #{@description.inspect}, fields:"\
      " #{@fields.inspect}, type: #{@type.inspect}, method: #{@method.inspect}, address:"\
      " #{@address.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
