# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # One or more required fields, as discovered by `POST
  # /instruments/requirements/search` for the (country, currency,
  # electronic-wallet) combination.
  class EwalletField < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Classifies the field types submitted when creating or updating an
    # electronic-wallet [Instrument](page:resources/instruments) — for example,
    # the wallet's account ID, the registered phone number, or the recipient
    # name. Required fields vary by provider, country, and currency; discover
    # them via `POST /instruments/requirements/search`.
    # @return [String]
    attr_accessor :key

    # Value for the electronic wallet field
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['key'] = 'key'
      @_hash['value'] = 'value'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(key:, value:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @key = key
      @value = value
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      key = hash.key?('key') ? hash['key'] : nil
      value = hash.key?('value') ? hash['value'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      EwalletField.new(key: key,
                       value: value,
                       additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [EwalletField | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.key,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.value,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['key'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['value'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} key: #{@key}, value: #{@value}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} key: #{@key.inspect}, value: #{@value.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
