# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # EwalletRequirementFormat Model.
  class EwalletRequirementFormat < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Example of a requirement generated from the validator(s)
    # @return [String]
    attr_accessor :example

    # Array of legend items explaining field format placeholders
    # @return [Array[EwalletRequirementFormatLegend]]
    attr_accessor :legend

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['example'] = 'example'
      @_hash['legend'] = 'legend'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        example
        legend
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(example: SKIP, legend: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @example = example unless example == SKIP
      @legend = legend unless legend == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      example = hash.key?('example') ? hash['example'] : SKIP
      # Parameter is an array, so we need to iterate through it
      legend = nil
      unless hash['legend'].nil?
        legend = []
        hash['legend'].each do |structure|
          legend << (EwalletRequirementFormatLegend.from_hash(structure) if structure)
        end
      end

      legend = SKIP unless hash.key?('legend')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      EwalletRequirementFormat.new(example: example,
                                   legend: legend,
                                   additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [EwalletRequirementFormat | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} example: #{@example}, legend: #{@legend}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} example: #{@example.inspect}, legend: #{@legend.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
