# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Validator type for a required electronic-wallet field.
  class EwalletRequirementValidator < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Kind of validation rule attached to a required field on a bank-account or
    # electronic-wallet [Instrument](page:resources/instruments) — `LENGTH`
    # (field length constraints), `REGEX` (pattern match), `RANGE` (numeric
    # range), `REQUIRED` (field must be present), or `UNDEFINED`. Returned by
    # `POST /instruments/requirements/search` so client UIs can validate input
    # before submission. See [Bank Account Field
    # Types](page:additional-api-information/bank-account-field-types) for the
    # field set these validators apply to.
    # @return [String]
    attr_accessor :validator_type

    # Validation regular expression
    # @return [String]
    attr_accessor :expression

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['validator_type'] = 'validatorType'
      @_hash['expression'] = 'expression'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        validator_type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(expression:, validator_type: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @validator_type = validator_type unless validator_type == SKIP
      @expression = expression
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      expression = hash.key?('expression') ? hash['expression'] : nil
      validator_type = hash.key?('validatorType') ? hash['validatorType'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      EwalletRequirementValidator.new(expression: expression,
                                      validator_type: validator_type,
                                      additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [EwalletRequirementValidator | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.expression,
                                     ->(val) { val.instance_of? String })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['expression'],
                            ->(val) { val.instance_of? String })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} validator_type: #{@validator_type}, expression: #{@expression},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} validator_type: #{@validator_type.inspect}, expression:"\
      " #{@expression.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
