# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Fee distribution details including amount, currency, and responsibility
  class FeeDistribution < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Allocated money to be sent in the transaction, represented as a string to
    # preserve decimal precision. On transfer-quote responses this value is
    # **always non-negative**, regardless of transfer direction. ([learn
    # more](page:concepts/monetary-precision#quote-responses-are-always-non-nega
    # tive))
    # @return [String]
    attr_accessor :amount

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # Localized description of the fee, in the language specified by the
    # request's Accept-Language header. Falls back to en-US if the requested
    # language is unavailable.
    # @return [String]
    attr_accessor :description

    # Combination of the amount and currency type. On transfer-quote responses
    # this string is **always sign-free** (never contains `-`, `(`, or `)`) — it
    # can be rendered directly without further sign-stripping. ([learn
    # more](page:concepts/monetary-precision#quote-responses-are-always-non-nega
    # tive))
    # @return [String]
    attr_accessor :formatted_amount

    # Fee percentage that the responsible account pays, represented as a string
    # to preserve decimal precision ([learn
    # more](page:concepts/monetary-precision))
    # @return [String]
    attr_accessor :percentage

    # Identifies which party bears the cost of a fee on a
    # [Receipt](page:resources/receipts) — `COMPANY` (the program's funding
    # account is debited), `USER` (the payee's wallet or card is debited),
    # `PAYQUICKER` (PayQuicker absorbs the fee), or `UNDEFINED`. Configured per
    # fee on the program's fee schedule.
    # @return [String]
    attr_accessor :responsibility

    # How a fee's responsibility is determined — `SCHEDULE` (the standard case,
    # derived from the program's configured fee schedule) or `CREDIT` (the fee
    # is offset against a fee credit). Appears alongside the `feeResponsibility`
    # party on a [Receipt](page:resources/receipts) line item.
    # @return [String]
    attr_accessor :responsibility_source

    # Token identifying the source of funds — typically a user-wallet token
    # (`user-`), a company funding-account token (`acct-`), or a prepaid-card
    # destination token (`dest-`).
    # @return [String]
    attr_accessor :source_token

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount'] = 'amount'
      @_hash['currency'] = 'currency'
      @_hash['description'] = 'description'
      @_hash['formatted_amount'] = 'formattedAmount'
      @_hash['percentage'] = 'percentage'
      @_hash['responsibility'] = 'responsibility'
      @_hash['responsibility_source'] = 'responsibilitySource'
      @_hash['source_token'] = 'sourceToken'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        amount
        currency
        description
        formatted_amount
        percentage
        responsibility
        responsibility_source
        source_token
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(amount: SKIP, currency: 'USD', description: SKIP,
                   formatted_amount: '$0.05 USD', percentage: SKIP,
                   responsibility: SKIP, responsibility_source: SKIP,
                   source_token: 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860',
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @amount = amount unless amount == SKIP
      @currency = currency unless currency == SKIP
      @description = description unless description == SKIP
      @formatted_amount = formatted_amount unless formatted_amount == SKIP
      @percentage = percentage unless percentage == SKIP
      @responsibility = responsibility unless responsibility == SKIP
      @responsibility_source = responsibility_source unless responsibility_source == SKIP
      @source_token = source_token unless source_token == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      currency = hash['currency'] ||= 'USD'
      description = hash.key?('description') ? hash['description'] : SKIP
      formatted_amount = hash['formattedAmount'] ||= '$0.05 USD'
      percentage = hash.key?('percentage') ? hash['percentage'] : SKIP
      responsibility =
        hash.key?('responsibility') ? hash['responsibility'] : SKIP
      responsibility_source =
        hash.key?('responsibilitySource') ? hash['responsibilitySource'] : SKIP
      source_token =
        hash['sourceToken'] ||= 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860'

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      FeeDistribution.new(amount: amount,
                          currency: currency,
                          description: description,
                          formatted_amount: formatted_amount,
                          percentage: percentage,
                          responsibility: responsibility,
                          responsibility_source: responsibility_source,
                          source_token: source_token,
                          additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [FeeDistribution | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount}, currency: #{@currency}, description: #{@description},"\
      " formatted_amount: #{@formatted_amount}, percentage: #{@percentage}, responsibility:"\
      " #{@responsibility}, responsibility_source: #{@responsibility_source}, source_token:"\
      " #{@source_token}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount.inspect}, currency: #{@currency.inspect}, description:"\
      " #{@description.inspect}, formatted_amount: #{@formatted_amount.inspect}, percentage:"\
      " #{@percentage.inspect}, responsibility: #{@responsibility.inspect}, responsibility_source:"\
      " #{@responsibility_source.inspect}, source_token: #{@source_token.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
