# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Fee configuration including category and distribution details. All monetary
  # fields within this object (`totalAmount`, `transactionAmount`,
  # `valueAmount`, and the `amount` on each distribution entry) are **always
  # non-negative** on responses. ([learn
  # more](page:concepts/monetary-precision#quote-responses-are-always-non-negati
  # ve))
  class FeeConfiguration < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # High-level category for a transactional record on a
    # [Receipt](page:resources/receipts) — `COMPANY` (a company /
    # funding-account-side entry) or `USER` (a payee-side entry). Used in
    # receipt-detail breakdowns to identify which party of a transaction the
    # line item describes. See [Receipt
    # Details](page:additional-api-information/receipt-details) for the full
    # breakdown structure.
    # @return [String]
    attr_accessor :category

    # Array of fee distribution details for each responsible party
    # @return [Array[FeeDistribution]]
    attr_accessor :distribution

    # What triggered a fee — `TRANSACTION` (the fee was generated by a
    # money-movement event such as a bank transfer or card purchase) or `USER`
    # (the fee was generated by a user-driven action such as account enrollment
    # or paper-statement request). Appears on [Receipt](page:resources/receipts)
    # line items so reconciliation pipelines can group fees by origin.
    # @return [String]
    attr_accessor :source

    # Total amount of money for all transactions, represented as a string to
    # preserve decimal precision ([learn
    # more](page:concepts/monetary-precision))
    # @return [String]
    attr_accessor :total_amount

    # Total amount of money for the transaction, represented as a string to
    # preserve decimal precision ([learn
    # more](page:concepts/monetary-precision))
    # @return [String]
    attr_accessor :transaction_amount

    # Type of fee assessed against an account, wallet, or prepaid card —
    # examples include `BANK_TRANSFER`, `INSTANT_PAYMENT`,
    # `PLASTIC_CARD_ISSUANCE`, `MONTHLY_MAINTENANCE_ACTIVE_ACCOUNT`,
    # `FOREIGN_EXCHANGE_CONVERSION`, and many more. Each fee on a
    # [Receipt](page:resources/receipts) carries this identifier so it can be
    # reconciled against the program's fee schedule. The exact set of fees a
    # program is subject to is configured by PayQuicker at onboarding.
    # @return [String]
    attr_accessor :type

    # Value of the target resource, represented as a string to preserve decimal
    # precision ([learn more](page:concepts/monetary-precision))
    # @return [String]
    attr_accessor :value_amount

    # How a fee amount is calculated — `STATIC` (a fixed amount regardless of
    # transaction size) or `PERCENTAGE` (a percentage of the transaction
    # amount). Surfaced on [Receipt](page:resources/receipts) line items
    # alongside the `[__Fees](page:additional-api-information/receipt-details)`
    # identifier so the calculation can be reconciled against the program's fee
    # schedule.
    # @return [String]
    attr_accessor :value_type

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :destination_country

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :destination_currency

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['category'] = 'category'
      @_hash['distribution'] = 'distribution'
      @_hash['source'] = 'source'
      @_hash['total_amount'] = 'totalAmount'
      @_hash['transaction_amount'] = 'transactionAmount'
      @_hash['type'] = 'type'
      @_hash['value_amount'] = 'valueAmount'
      @_hash['value_type'] = 'valueType'
      @_hash['destination_country'] = 'destinationCountry'
      @_hash['destination_currency'] = 'destinationCurrency'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        category
        distribution
        source
        total_amount
        transaction_amount
        type
        value_amount
        value_type
        destination_country
        destination_currency
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(category: SKIP, distribution: SKIP, source: SKIP,
                   total_amount: SKIP, transaction_amount: SKIP, type: SKIP,
                   value_amount: SKIP, value_type: SKIP,
                   destination_country: SKIP, destination_currency: 'USD',
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @category = category unless category == SKIP
      @distribution = distribution unless distribution == SKIP
      @source = source unless source == SKIP
      @total_amount = total_amount unless total_amount == SKIP
      @transaction_amount = transaction_amount unless transaction_amount == SKIP
      @type = type unless type == SKIP
      @value_amount = value_amount unless value_amount == SKIP
      @value_type = value_type unless value_type == SKIP
      @destination_country = destination_country unless destination_country == SKIP
      @destination_currency = destination_currency unless destination_currency == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      category = hash.key?('category') ? hash['category'] : SKIP
      # Parameter is an array, so we need to iterate through it
      distribution = nil
      unless hash['distribution'].nil?
        distribution = []
        hash['distribution'].each do |structure|
          distribution << (FeeDistribution.from_hash(structure) if structure)
        end
      end

      distribution = SKIP unless hash.key?('distribution')
      source = hash.key?('source') ? hash['source'] : SKIP
      total_amount = hash.key?('totalAmount') ? hash['totalAmount'] : SKIP
      transaction_amount =
        hash.key?('transactionAmount') ? hash['transactionAmount'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      value_amount = hash.key?('valueAmount') ? hash['valueAmount'] : SKIP
      value_type = hash.key?('valueType') ? hash['valueType'] : SKIP
      destination_country =
        hash.key?('destinationCountry') ? hash['destinationCountry'] : SKIP
      destination_currency = hash['destinationCurrency'] ||= 'USD'

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      FeeConfiguration.new(category: category,
                           distribution: distribution,
                           source: source,
                           total_amount: total_amount,
                           transaction_amount: transaction_amount,
                           type: type,
                           value_amount: value_amount,
                           value_type: value_type,
                           destination_country: destination_country,
                           destination_currency: destination_currency,
                           additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [FeeConfiguration | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} category: #{@category}, distribution: #{@distribution}, source: #{@source},"\
      " total_amount: #{@total_amount}, transaction_amount: #{@transaction_amount}, type:"\
      " #{@type}, value_amount: #{@value_amount}, value_type: #{@value_type}, destination_country:"\
      " #{@destination_country}, destination_currency: #{@destination_currency},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} category: #{@category.inspect}, distribution: #{@distribution.inspect},"\
      " source: #{@source.inspect}, total_amount: #{@total_amount.inspect}, transaction_amount:"\
      " #{@transaction_amount.inspect}, type: #{@type.inspect}, value_amount:"\
      " #{@value_amount.inspect}, value_type: #{@value_type.inspect}, destination_country:"\
      " #{@destination_country.inspect}, destination_currency: #{@destination_currency.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
