# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module PqApiV2
  # A batch payment job for a Gateway program — one or more
  # [Payments](page:resources/transfers) submitted as a single CSV-driven
  # request, with each row processed independently. Counterpart to
  # `PortalPaymentJob` for Hosted Portal programs. See [Payment
  # Jobs](page:resources/payment-jobs).
  class GatewayPaymentJob < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Transfer is scheduled and will not process before this time. ISO 8601
    # format.
    # @return [DateTime]
    attr_accessor :not_before

    # Transfer expires if not accepted prior to this time. ISO 8601 format.
    # @return [DateTime]
    attr_accessor :not_after

    # Transfer expires if not accepted prior to this time. ISO 8601 format.
    # @return [Array[GatewayPaymentJobQuote]]
    attr_accessor :items

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['not_before'] = 'notBefore'
      @_hash['not_after'] = 'notAfter'
      @_hash['items'] = 'items'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        not_before
        not_after
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(items:, not_before: SKIP, not_after: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @not_before = not_before unless not_before == SKIP
      @not_after = not_after unless not_after == SKIP
      @items = items
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      items = nil
      unless hash['items'].nil?
        items = []
        hash['items'].each do |structure|
          items << (GatewayPaymentJobQuote.from_hash(structure) if structure)
        end
      end

      items = nil unless hash.key?('items')
      not_before = if hash.key?('notBefore')
                     (DateTimeHelper.from_rfc3339(hash['notBefore']) if hash['notBefore'])
                   else
                     SKIP
                   end
      not_after = if hash.key?('notAfter')
                    (DateTimeHelper.from_rfc3339(hash['notAfter']) if hash['notAfter'])
                  else
                    SKIP
                  end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      GatewayPaymentJob.new(items: items,
                            not_before: not_before,
                            not_after: not_after,
                            additional_properties: additional_properties)
    end

    def to_custom_not_before
      DateTimeHelper.to_rfc3339(not_before)
    end

    def to_custom_not_after
      DateTimeHelper.to_rfc3339(not_after)
    end

    # Validates an instance of the object from a given value.
    # @param [GatewayPaymentJob | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.items,
                                     ->(val) { GatewayPaymentJobQuote.validate(val) },
                                     is_model_hash: true,
                                     is_inner_model_hash: true)
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['items'],
                            ->(val) { GatewayPaymentJobQuote.validate(val) },
                            is_model_hash: true,
                            is_inner_model_hash: true)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} not_before: #{@not_before}, not_after: #{@not_after}, items: #{@items},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} not_before: #{@not_before.inspect}, not_after: #{@not_after.inspect},"\
      " items: #{@items.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
