# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Quote returned by `POST /transfers` with `transferType: TRANSFER` for a
  # Gateway program — bank transfers, account-to-account transfers, and prepaid
  # card loads. Accept with `POST /transfers/{token}/accept`. See
  # [Transfers](page:resources/transfers), [Transfer
  # Types](page:additional-api-information/transfer-types), and [Transfer Method
  # Types](page:additional-api-information/transfer-method-types).
  class GatewayTransferQuote < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token identifying the source of funds — typically a user-wallet token
    # (`user-`), a company funding-account token (`acct-`), or a prepaid-card
    # destination token (`dest-`).
    # @return [String]
    attr_accessor :source_token

    # Token identifying the destination of funds — a bank-account or
    # electronic-wallet [Instrument](page:resources/instruments), or a [Prepaid
    # Card](page:resources/prepaid-cards). Prefix `dest-`.
    # @return [String]
    attr_accessor :destination_token

    # Allocated money to be sent in the transaction, represented as a string to
    # preserve decimal precision. On transfer-quote responses this value is
    # **always non-negative**, regardless of transfer direction — direction is
    # conveyed by `transferType`, not by sign. ([learn
    # more](page:concepts/monetary-precision#quote-responses-are-always-non-nega
    # tive))
    # @return [String]
    attr_accessor :amount

    # Unique value provided by the client for the transfer, utilized for
    # reference and deduplication.
    # @return [String]
    attr_accessor :client_transfer_ref

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # Optional comments visible to the user.
    # @return [String]
    attr_accessor :note

    # Optional internal memo, not visible to the user.
    # @return [String]
    attr_accessor :memo

    # Type of
    # [lockside](page:additional-api-information/transfer-lockside-types) for
    # transfers.
    # @return [String]
    attr_accessor :lockside

    # Underlying rail used to settle a `transferType: TRANSFER` to a
    # bank-account or electronic-wallet
    # [Instrument](page:resources/instruments). Examples: `IACH` (international
    # ACH), `WIRE`, `LOCAL`. Available methods depend on the destination's
    # country and currency — discover them via `POST
    # /instruments/requirements/search`. See [Transfer Method
    # Types](page:additional-api-information/transfer-method-types) for the full
    # list.
    # @return [String]
    attr_accessor :method

    # How a transfer quote is processed after creation — required on every
    # transfer quote body. `AUTO_ACCEPT` causes the quote to be accepted and
    # executed in a single call — a fire-and-forget disbursement.
    # `MANUAL_ACCEPT` leaves the quote in `PENDING_ACCEPTANCE` and requires an
    # explicit `POST /transfers/{token}/accept` to execute it. See
    # [Transfers](page:resources/transfers) for the quote / accept lifecycle.
    # @return [String]
    attr_accessor :acceptance_mode

    # Discriminator value identifying this as a transfer quote.
    # @return [TransferType7]
    attr_accessor :transfer_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source_token'] = 'sourceToken'
      @_hash['destination_token'] = 'destinationToken'
      @_hash['amount'] = 'amount'
      @_hash['client_transfer_ref'] = 'clientTransferRef'
      @_hash['currency'] = 'currency'
      @_hash['note'] = 'note'
      @_hash['memo'] = 'memo'
      @_hash['lockside'] = 'lockside'
      @_hash['method'] = 'method'
      @_hash['acceptance_mode'] = 'acceptanceMode'
      @_hash['transfer_type'] = 'transferType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        currency
        note
        memo
        lockside
        method
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(
      source_token: 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860',
      destination_token: 'dest-631b200f-665d-4dbe-bd01-3063c9dec97d', amount:,
      client_transfer_ref:, acceptance_mode:, transfer_type:, currency: 'USD',
      note: SKIP, memo: SKIP, lockside: SKIP, method: SKIP,
      additional_properties: nil
    )
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @source_token = source_token
      @destination_token = destination_token
      @amount = amount
      @client_transfer_ref = client_transfer_ref
      @currency = currency unless currency == SKIP
      @note = note unless note == SKIP
      @memo = memo unless memo == SKIP
      @lockside = lockside unless lockside == SKIP
      @method = method unless method == SKIP
      @acceptance_mode = acceptance_mode
      @transfer_type = transfer_type
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source_token =
        hash['sourceToken'] ||= 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860'
      destination_token =
        hash['destinationToken'] ||= 'dest-631b200f-665d-4dbe-bd01-3063c9dec97d'
      amount = hash.key?('amount') ? hash['amount'] : nil
      client_transfer_ref =
        hash.key?('clientTransferRef') ? hash['clientTransferRef'] : nil
      acceptance_mode =
        hash.key?('acceptanceMode') ? hash['acceptanceMode'] : nil
      transfer_type = hash.key?('transferType') ? hash['transferType'] : nil
      currency = hash['currency'] ||= 'USD'
      note = hash.key?('note') ? hash['note'] : SKIP
      memo = hash.key?('memo') ? hash['memo'] : SKIP
      lockside = hash.key?('lockside') ? hash['lockside'] : SKIP
      method = hash.key?('method') ? hash['method'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      GatewayTransferQuote.new(source_token: source_token,
                               destination_token: destination_token,
                               amount: amount,
                               client_transfer_ref: client_transfer_ref,
                               acceptance_mode: acceptance_mode,
                               transfer_type: transfer_type,
                               currency: currency,
                               note: note,
                               memo: memo,
                               lockside: lockside,
                               method: method,
                               additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [GatewayTransferQuote | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.source_token,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.destination_token,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.amount,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.client_transfer_ref,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.acceptance_mode,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.transfer_type,
                                  ->(val) { TransferType7.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['sourceToken'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['destinationToken'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['amount'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['clientTransferRef'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['acceptanceMode'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['transferType'],
                                ->(val) { TransferType7.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} source_token: #{@source_token}, destination_token: #{@destination_token},"\
      " amount: #{@amount}, client_transfer_ref: #{@client_transfer_ref}, currency: #{@currency},"\
      " note: #{@note}, memo: #{@memo}, lockside: #{@lockside}, method: #{@method},"\
      " acceptance_mode: #{@acceptance_mode}, transfer_type: #{@transfer_type},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} source_token: #{@source_token.inspect}, destination_token:"\
      " #{@destination_token.inspect}, amount: #{@amount.inspect}, client_transfer_ref:"\
      " #{@client_transfer_ref.inspect}, currency: #{@currency.inspect}, note: #{@note.inspect},"\
      " memo: #{@memo.inspect}, lockside: #{@lockside.inspect}, method: #{@method.inspect},"\
      " acceptance_mode: #{@acceptance_mode.inspect}, transfer_type: #{@transfer_type.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
