# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module PqApiV2
  # An identity-verification check result attached to a
  # [User](page:resources/users) — captures the outcome of a single KYC
  # verification step (document validation, sanctions screening, etc.). See [KYC
  # Enums](page:additional-api-information/kyc-enums) for the result-type
  # catalog.
  class IdvCheckBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :token

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :user_token

    # Program-assigned identifier for the user. Used by Hosted Portal programs
    # (with `email`) to address payees in transactional and search bodies. See
    # [Scope Discriminator](page:concepts/scope-discriminator).
    # @return [String]
    attr_accessor :program_user_id

    # Provider-specific reference identifier for the identity-verification
    # check.
    # @return [String]
    attr_accessor :idv_provider_reference

    # Result type of identity verification. See [KYC
    # Enums](page:additional-api-information/kyc-enums).
    # @return [String]
    attr_accessor :idv_result

    # Sub-result type of identity verification — `HARD` (definitive outcome) or
    # `SOFT` (may require manual review). See [KYC
    # Enums](page:additional-api-information/kyc-enums).
    # @return [String]
    attr_accessor :idv_sub_result

    # Provider types of identity verification that can be used for performing
    # identity checks. See [KYC
    # Enums](page:additional-api-information/kyc-enums).
    # @return [String]
    attr_accessor :idv_provider

    # Date and time when the resource was created. ISO 8601 format.
    # @return [DateTime]
    attr_accessor :created_at

    # Raw, unprocessed output from the IDV provider for an [IDV
    # check](page:resources/idv-checks). Surfaced for diagnostics and audit; the
    # typed result fields on the IDV-check record are the normalized
    # customer-facing surface.
    # @return [String]
    attr_accessor :raw

    # Type of verification used for performing an identity check. See [IDV
    # Checks](page:resources/idv-checks) and [KYC
    # Enums](page:additional-api-information/kyc-enums).
    # @return [String]
    attr_accessor :idv_check_type

    # Disposition type of identity verification. See [KYC
    # Enums](page:additional-api-information/kyc-enums).
    # @return [String]
    attr_accessor :idv_disposition

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['user_token'] = 'userToken'
      @_hash['program_user_id'] = 'programUserId'
      @_hash['idv_provider_reference'] = 'idvProviderReference'
      @_hash['idv_result'] = 'idvResult'
      @_hash['idv_sub_result'] = 'idvSubResult'
      @_hash['idv_provider'] = 'idvProvider'
      @_hash['created_at'] = 'createdAt'
      @_hash['raw'] = 'raw'
      @_hash['idv_check_type'] = 'idvCheckType'
      @_hash['idv_disposition'] = 'idvDisposition'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        idv_sub_result
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(token:, user_token:, program_user_id:,
                   idv_provider_reference:, idv_result:, idv_provider:,
                   created_at:, raw:, idv_check_type:, idv_disposition:,
                   idv_sub_result: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @token = token
      @user_token = user_token
      @program_user_id = program_user_id
      @idv_provider_reference = idv_provider_reference
      @idv_result = idv_result
      @idv_sub_result = idv_sub_result unless idv_sub_result == SKIP
      @idv_provider = idv_provider
      @created_at = created_at
      @raw = raw
      @idv_check_type = idv_check_type
      @idv_disposition = idv_disposition
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : nil
      user_token = hash.key?('userToken') ? hash['userToken'] : nil
      program_user_id = hash.key?('programUserId') ? hash['programUserId'] : nil
      idv_provider_reference =
        hash.key?('idvProviderReference') ? hash['idvProviderReference'] : nil
      idv_result = hash.key?('idvResult') ? hash['idvResult'] : nil
      idv_provider = hash.key?('idvProvider') ? hash['idvProvider'] : nil
      created_at = if hash.key?('createdAt')
                     (DateTimeHelper.from_rfc3339(hash['createdAt']) if hash['createdAt'])
                   end
      raw = hash.key?('raw') ? hash['raw'] : nil
      idv_check_type = hash.key?('idvCheckType') ? hash['idvCheckType'] : nil
      idv_disposition =
        hash.key?('idvDisposition') ? hash['idvDisposition'] : nil
      idv_sub_result = hash.key?('idvSubResult') ? hash['idvSubResult'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      IdvCheckBase.new(token: token,
                       user_token: user_token,
                       program_user_id: program_user_id,
                       idv_provider_reference: idv_provider_reference,
                       idv_result: idv_result,
                       idv_provider: idv_provider,
                       created_at: created_at,
                       raw: raw,
                       idv_check_type: idv_check_type,
                       idv_disposition: idv_disposition,
                       idv_sub_result: idv_sub_result,
                       additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, user_token: #{@user_token}, program_user_id:"\
      " #{@program_user_id}, idv_provider_reference: #{@idv_provider_reference}, idv_result:"\
      " #{@idv_result}, idv_sub_result: #{@idv_sub_result}, idv_provider: #{@idv_provider},"\
      " created_at: #{@created_at}, raw: #{@raw}, idv_check_type: #{@idv_check_type},"\
      " idv_disposition: #{@idv_disposition}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, user_token: #{@user_token.inspect},"\
      " program_user_id: #{@program_user_id.inspect}, idv_provider_reference:"\
      " #{@idv_provider_reference.inspect}, idv_result: #{@idv_result.inspect}, idv_sub_result:"\
      " #{@idv_sub_result.inspect}, idv_provider: #{@idv_provider.inspect}, created_at:"\
      " #{@created_at.inspect}, raw: #{@raw.inspect}, idv_check_type: #{@idv_check_type.inspect},"\
      " idv_disposition: #{@idv_disposition.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
