# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Request for creating or updating an individual user
  class IndividualUser < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Auto-generated unique identifier representing a program, prefixed with
    # prog-
    # @return [String]
    attr_accessor :program_token

    # Program-assigned identifier for the user. Used by Hosted Portal programs
    # (with `email`) to address payees in transactional and search bodies. See
    # [Scope Discriminator](page:concepts/scope-discriminator).
    # @return [String]
    attr_accessor :program_user_id

    # Contact email address for the user account.
    # @return [String]
    attr_accessor :email

    # First name
    # @return [String]
    attr_accessor :first_name

    # Last name
    # @return [String]
    attr_accessor :last_name

    # Date and time of birth in ISO 8601 format
    # @return [Date]
    attr_accessor :date_of_birth

    # Gender as a user self-identifies. Optional on user creation; captured for
    # KYC and reporting where required by jurisdiction. See [KYC
    # Enums](page:additional-api-information/kyc-enums) for the full value list.
    # @return [String]
    attr_accessor :gender

    # Language type in IETF's BCP 47 format. See [Supported
    # Languages](page:additional-api-information/supported-languages) for the
    # full list.
    # @return [String]
    attr_accessor :language

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :country_of_birth

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :country_of_nationality

    # Tax-residency status of a user, used by the platform's tax-services
    # pipeline (where the program enables it) and by jurisdictional reporting.
    # See [KYC Enums](page:additional-api-information/kyc-enums) for the full
    # value list.
    # @return [String]
    attr_accessor :tax_resident_status

    # Indicates the type of government ID submitted for user verification
    # purposes. See [Government ID
    # Types](page:additional-api-information/government-id-types) for the full
    # list.
    # @return [String]
    attr_accessor :government_id_type

    # Government-issued identification number with a maximum length of 20
    # characters
    # @return [String]
    attr_accessor :government_id

    # Job title or occupation
    # @return [String]
    attr_accessor :occupation_title

    # Occupation category recorded on a [user](page:resources/users) profile.
    # Used in KYC and reporting. See [KYC
    # Enums](page:additional-api-information/kyc-enums) for the full value list.
    # @return [String]
    attr_accessor :occupation_type

    # Auto-generated unique identifier representing a user, prefixed with
    # `user-`.
    # @return [String]
    attr_accessor :primary_user_token

    # INDIVIDUAL requires RESIDENTIAL and MAILING.
    # @return [Array[AddressObject]]
    attr_accessor :addresses

    # PRIMARY is required.
    # @return [Array[PhoneNumberObject]]
    attr_accessor :phone_numbers

    # Discriminator identifying this as an individual user.
    # @return [UserType2]
    attr_accessor :user_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['program_token'] = 'programToken'
      @_hash['program_user_id'] = 'programUserId'
      @_hash['email'] = 'email'
      @_hash['first_name'] = 'firstName'
      @_hash['last_name'] = 'lastName'
      @_hash['date_of_birth'] = 'dateOfBirth'
      @_hash['gender'] = 'gender'
      @_hash['language'] = 'language'
      @_hash['country_of_birth'] = 'countryOfBirth'
      @_hash['country_of_nationality'] = 'countryOfNationality'
      @_hash['tax_resident_status'] = 'taxResidentStatus'
      @_hash['government_id_type'] = 'governmentIdType'
      @_hash['government_id'] = 'governmentId'
      @_hash['occupation_title'] = 'occupationTitle'
      @_hash['occupation_type'] = 'occupationType'
      @_hash['primary_user_token'] = 'primaryUserToken'
      @_hash['addresses'] = 'addresses'
      @_hash['phone_numbers'] = 'phoneNumbers'
      @_hash['user_type'] = 'userType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        gender
        language
        tax_resident_status
        government_id_type
        government_id
        occupation_title
        occupation_type
        primary_user_token
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(program_token:, program_user_id:, email:, first_name:,
                   last_name:, date_of_birth:, country_of_birth:,
                   country_of_nationality:, addresses:, phone_numbers:,
                   user_type:, gender: SKIP, language: 'en-US',
                   tax_resident_status: SKIP, government_id_type: SKIP,
                   government_id: SKIP, occupation_title: SKIP,
                   occupation_type: SKIP, primary_user_token: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @program_token = program_token
      @program_user_id = program_user_id
      @email = email
      @first_name = first_name
      @last_name = last_name
      @date_of_birth = date_of_birth
      @gender = gender unless gender == SKIP
      @language = language unless language == SKIP
      @country_of_birth = country_of_birth
      @country_of_nationality = country_of_nationality
      @tax_resident_status = tax_resident_status unless tax_resident_status == SKIP
      @government_id_type = government_id_type unless government_id_type == SKIP
      @government_id = government_id unless government_id == SKIP
      @occupation_title = occupation_title unless occupation_title == SKIP
      @occupation_type = occupation_type unless occupation_type == SKIP
      @primary_user_token = primary_user_token unless primary_user_token == SKIP
      @addresses = addresses
      @phone_numbers = phone_numbers
      @user_type = user_type
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      program_token = hash.key?('programToken') ? hash['programToken'] : nil
      program_user_id = hash.key?('programUserId') ? hash['programUserId'] : nil
      email = hash.key?('email') ? hash['email'] : nil
      first_name = hash.key?('firstName') ? hash['firstName'] : nil
      last_name = hash.key?('lastName') ? hash['lastName'] : nil
      date_of_birth = hash.key?('dateOfBirth') ? hash['dateOfBirth'] : nil
      country_of_birth =
        hash.key?('countryOfBirth') ? hash['countryOfBirth'] : nil
      country_of_nationality =
        hash.key?('countryOfNationality') ? hash['countryOfNationality'] : nil
      # Parameter is an array, so we need to iterate through it
      addresses = nil
      unless hash['addresses'].nil?
        addresses = []
        hash['addresses'].each do |structure|
          addresses << (AddressObject.from_hash(structure) if structure)
        end
      end

      addresses = nil unless hash.key?('addresses')
      # Parameter is an array, so we need to iterate through it
      phone_numbers = nil
      unless hash['phoneNumbers'].nil?
        phone_numbers = []
        hash['phoneNumbers'].each do |structure|
          phone_numbers << (PhoneNumberObject.from_hash(structure) if structure)
        end
      end

      phone_numbers = nil unless hash.key?('phoneNumbers')
      user_type = hash.key?('userType') ? hash['userType'] : nil
      gender = hash.key?('gender') ? hash['gender'] : SKIP
      language = hash['language'] ||= 'en-US'
      tax_resident_status =
        hash.key?('taxResidentStatus') ? hash['taxResidentStatus'] : SKIP
      government_id_type =
        hash.key?('governmentIdType') ? hash['governmentIdType'] : SKIP
      government_id = hash.key?('governmentId') ? hash['governmentId'] : SKIP
      occupation_title =
        hash.key?('occupationTitle') ? hash['occupationTitle'] : SKIP
      occupation_type =
        hash.key?('occupationType') ? hash['occupationType'] : SKIP
      primary_user_token =
        hash.key?('primaryUserToken') ? hash['primaryUserToken'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      IndividualUser.new(program_token: program_token,
                         program_user_id: program_user_id,
                         email: email,
                         first_name: first_name,
                         last_name: last_name,
                         date_of_birth: date_of_birth,
                         country_of_birth: country_of_birth,
                         country_of_nationality: country_of_nationality,
                         addresses: addresses,
                         phone_numbers: phone_numbers,
                         user_type: user_type,
                         gender: gender,
                         language: language,
                         tax_resident_status: tax_resident_status,
                         government_id_type: government_id_type,
                         government_id: government_id,
                         occupation_title: occupation_title,
                         occupation_type: occupation_type,
                         primary_user_token: primary_user_token,
                         additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [IndividualUser | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.program_token,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.program_user_id,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.email,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.first_name,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.last_name,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.date_of_birth,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.country_of_birth,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.country_of_nationality,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.addresses,
                                  ->(val) { AddressObject.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.phone_numbers,
                                  ->(val) { PhoneNumberObject.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.user_type,
                                  ->(val) { UserType2.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['programToken'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['programUserId'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['email'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['firstName'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['lastName'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['dateOfBirth'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['countryOfBirth'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['countryOfNationality'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['addresses'],
                                ->(val) { AddressObject.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['phoneNumbers'],
                                ->(val) { PhoneNumberObject.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['userType'],
                                ->(val) { UserType2.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} program_token: #{@program_token}, program_user_id: #{@program_user_id},"\
      " email: #{@email}, first_name: #{@first_name}, last_name: #{@last_name}, date_of_birth:"\
      " #{@date_of_birth}, gender: #{@gender}, language: #{@language}, country_of_birth:"\
      " #{@country_of_birth}, country_of_nationality: #{@country_of_nationality},"\
      " tax_resident_status: #{@tax_resident_status}, government_id_type: #{@government_id_type},"\
      " government_id: #{@government_id}, occupation_title: #{@occupation_title}, occupation_type:"\
      " #{@occupation_type}, primary_user_token: #{@primary_user_token}, addresses: #{@addresses},"\
      " phone_numbers: #{@phone_numbers}, user_type: #{@user_type}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} program_token: #{@program_token.inspect}, program_user_id:"\
      " #{@program_user_id.inspect}, email: #{@email.inspect}, first_name: #{@first_name.inspect},"\
      " last_name: #{@last_name.inspect}, date_of_birth: #{@date_of_birth.inspect}, gender:"\
      " #{@gender.inspect}, language: #{@language.inspect}, country_of_birth:"\
      " #{@country_of_birth.inspect}, country_of_nationality: #{@country_of_nationality.inspect},"\
      " tax_resident_status: #{@tax_resident_status.inspect}, government_id_type:"\
      " #{@government_id_type.inspect}, government_id: #{@government_id.inspect},"\
      " occupation_title: #{@occupation_title.inspect}, occupation_type:"\
      " #{@occupation_type.inspect}, primary_user_token: #{@primary_user_token.inspect},"\
      " addresses: #{@addresses.inspect}, phone_numbers: #{@phone_numbers.inspect}, user_type:"\
      " #{@user_type.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
