# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module PqApiV2
  # InvitationJobUpdatedWebhookRequest Model.
  class InvitationJobUpdatedWebhookRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Namespaced event identifier on a webhook delivery — encodes the resource
    # and lifecycle action in a single dotted token (e.g.,
    # `BANKACCOUNTS.CREATED`, `PAYMENTS.UPDATED.STATUS.COMPLETE`,
    # `USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE`). Client handlers route on
    # this value to dispatch to per-event business logic. See the
    # [Webhooks](page:concepts/available-webhooks) catalog for the full
    # per-program-type matrix and [Event
    # Notifications](page:concepts/working-with-event-notifications) for retry /
    # idempotency semantics.
    # @return [WebhookNamespaces]
    attr_accessor :event_type

    # Invitation job — a CSV-uploaded batch that produces one invitation per
    # row. Carries the file metadata (filename, total / valid / invalid record
    # counts) and a status that tracks the job from `CREATED` through
    # `COMPLETED`. The individual invitations produced by the job are searchable
    # via [`POST /invitations/search`]($e/Invitations/Search%20Invitations) with
    # a job-token filter. Token prefix `jobs-`. **Invitation Jobs are a Hosted
    # Portal concept only**. See [Invitation
    # Jobs](page:resources/invitation-jobs).
    # @return [InvitationJobBase]
    attr_accessor :payload

    # Webhook event timestamp.
    # @return [DateTime]
    attr_accessor :timestamp

    # Metadata wrapper returned on every webhook delivery — carries the event
    # namespace, delivery ID, signature inputs, and timestamp. See [Event
    # Notifications](page:concepts/working-with-event-notifications) for retry /
    # idempotency / replay-attack handling.
    # @return [WebhookMetadata]
    attr_accessor :meta

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['event_type'] = 'eventType'
      @_hash['payload'] = 'payload'
      @_hash['timestamp'] = 'timestamp'
      @_hash['meta'] = 'meta'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(event_type:, payload:, timestamp:, meta:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @event_type = event_type
      @payload = payload
      @timestamp = timestamp
      @meta = meta
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      event_type = hash.key?('eventType') ? hash['eventType'] : nil
      payload = InvitationJobBase.from_hash(hash['payload']) if hash['payload']
      timestamp = if hash.key?('timestamp')
                    (DateTimeHelper.from_rfc3339(hash['timestamp']) if hash['timestamp'])
                  end
      meta = WebhookMetadata.from_hash(hash['meta']) if hash['meta']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      InvitationJobUpdatedWebhookRequest.new(event_type: event_type,
                                             payload: payload,
                                             timestamp: timestamp,
                                             meta: meta,
                                             additional_properties: additional_properties)
    end

    def to_custom_timestamp
      DateTimeHelper.to_rfc3339(timestamp)
    end

    # Validates an instance of the object from a given value.
    # @param [InvitationJobUpdatedWebhookRequest | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.event_type,
                                ->(val) { WebhookNamespaces.validate(val) }) and
            APIHelper.valid_type?(value.payload,
                                  ->(val) { InvitationJobBase.validate(val) },
                                  is_model_hash: true) and
            APIHelper.valid_type?(value.timestamp,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.meta,
                                  ->(val) { WebhookMetadata.validate(val) },
                                  is_model_hash: true)
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['eventType'],
                              ->(val) { WebhookNamespaces.validate(val) }) and
          APIHelper.valid_type?(value['payload'],
                                ->(val) { InvitationJobBase.validate(val) },
                                is_model_hash: true) and
          APIHelper.valid_type?(value['timestamp'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['meta'],
                                ->(val) { WebhookMetadata.validate(val) },
                                is_model_hash: true)
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} event_type: #{@event_type}, payload: #{@payload}, timestamp: #{@timestamp},"\
      " meta: #{@meta}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} event_type: #{@event_type.inspect}, payload: #{@payload.inspect},"\
      " timestamp: #{@timestamp.inspect}, meta: #{@meta.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
