# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Metadata items including timezone, language, and version information
  class MetadataItems < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Timezone of the datetime objects in the response
    # @return [String]
    attr_accessor :timezone

    # Language used for localized content in this response, determined by the
    # Accept-Language request header. Falls back to en-US if the requested
    # language is unavailable.
    # @return [String]
    attr_accessor :language

    # API version of the response object, in YYYY.MM.DD format
    # @return [String]
    attr_accessor :version

    # API version of the response object, in YYYY.MM.DD format
    # @return [String]
    attr_accessor :request_ref

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['timezone'] = 'timezone'
      @_hash['language'] = 'language'
      @_hash['version'] = 'version'
      @_hash['request_ref'] = 'requestRef'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(timezone:, language:, version:, request_ref:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @timezone = timezone
      @language = language
      @version = version
      @request_ref = request_ref
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      timezone = hash.key?('timezone') ? hash['timezone'] : nil
      language = hash.key?('language') ? hash['language'] : nil
      version = hash.key?('version') ? hash['version'] : nil
      request_ref = hash.key?('requestRef') ? hash['requestRef'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      MetadataItems.new(timezone: timezone,
                        language: language,
                        version: version,
                        request_ref: request_ref,
                        additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [MetadataItems | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.timezone,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.language,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.version,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.request_ref,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['timezone'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['language'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['version'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['requestRef'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} timezone: #{@timezone}, language: #{@language}, version: #{@version},"\
      " request_ref: #{@request_ref}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} timezone: #{@timezone.inspect}, language: #{@language.inspect}, version:"\
      " #{@version.inspect}, request_ref: #{@request_ref.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
