# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # A single sort row inside a `POST /jobs/payments/search` request body's
  # `sort` array. The `field` value comes from `PaymentJobSearchSortField`;
  # `direction` is `ASC` or `DESC` (see [Filtering &
  # Sorting](page:concepts/filtering-sorting)). Exactly one sort row is
  # supported. See [`Payment Job Search
  # Fields`](page:additional-api-information/payment-job-search-fields#sort-fiel
  # ds) for the catalog of sortable fields.
  class PaymentJobSearchSortItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Sortable fields for payment job search.
    # @return [String]
    attr_accessor :field

    # Sort direction. Defaults to descending.
    # @return [String]
    attr_accessor :direction

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['field'] = 'field'
      @_hash['direction'] = 'direction'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(field:, direction: 'DESC', additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @field = field
      @direction = direction
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      field = hash.key?('field') ? hash['field'] : nil
      direction = hash['direction'] ||= 'DESC'

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PaymentJobSearchSortItem.new(field: field,
                                   direction: direction,
                                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} field: #{@field}, direction: #{@direction}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} field: #{@field.inspect}, direction: #{@direction.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
