# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Quote for retracting a payment. Retractions do not take an amount because
  # they always attempt to recover the full balance of the original payment. If
  # insufficient funds are available, a partial retraction is performed and
  # subsequent retraction attempts can recover remaining amounts as balance
  # becomes available. Does not vary by program type — the payment being
  # retracted is identified by the path parameter.
  class PaymentRetractionQuote < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique value provided by the client for the transfer, utilized for
    # reference and deduplication.
    # @return [String]
    attr_accessor :payment_id

    # Unique value provided by the client for the payment retraction
    # @return [String]
    attr_accessor :client_retraction_ref

    # Optional internal memo, not visible to the user.
    # @return [String]
    attr_accessor :memo

    # Optional comments visible to the user.
    # @return [String]
    attr_accessor :note

    # How a transfer quote is processed after creation — required on every
    # transfer quote body. `AUTO_ACCEPT` causes the quote to be accepted and
    # executed in a single call — a fire-and-forget disbursement.
    # `MANUAL_ACCEPT` leaves the quote in `PENDING_ACCEPTANCE` and requires an
    # explicit `POST /transfers/{token}/accept` to execute it. See
    # [Transfers](page:resources/transfers) for the quote / accept lifecycle.
    # @return [String]
    attr_accessor :acceptance_mode

    # Discriminator value identifying this as a payment retraction quote.
    # @return [TransferType5]
    attr_accessor :transfer_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payment_id'] = 'paymentId'
      @_hash['client_retraction_ref'] = 'clientRetractionRef'
      @_hash['memo'] = 'memo'
      @_hash['note'] = 'note'
      @_hash['acceptance_mode'] = 'acceptanceMode'
      @_hash['transfer_type'] = 'transferType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        memo
        note
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payment_id:, client_retraction_ref:, acceptance_mode:,
                   transfer_type:, memo: SKIP, note: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @payment_id = payment_id
      @client_retraction_ref = client_retraction_ref
      @memo = memo unless memo == SKIP
      @note = note unless note == SKIP
      @acceptance_mode = acceptance_mode
      @transfer_type = transfer_type
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payment_id = hash.key?('paymentId') ? hash['paymentId'] : nil
      client_retraction_ref =
        hash.key?('clientRetractionRef') ? hash['clientRetractionRef'] : nil
      acceptance_mode =
        hash.key?('acceptanceMode') ? hash['acceptanceMode'] : nil
      transfer_type = hash.key?('transferType') ? hash['transferType'] : nil
      memo = hash.key?('memo') ? hash['memo'] : SKIP
      note = hash.key?('note') ? hash['note'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PaymentRetractionQuote.new(payment_id: payment_id,
                                 client_retraction_ref: client_retraction_ref,
                                 acceptance_mode: acceptance_mode,
                                 transfer_type: transfer_type,
                                 memo: memo,
                                 note: note,
                                 additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PaymentRetractionQuote | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.payment_id,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.client_retraction_ref,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.acceptance_mode,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.transfer_type,
                                  ->(val) { TransferType5.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['paymentId'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['clientRetractionRef'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['acceptanceMode'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['transferType'],
                                ->(val) { TransferType5.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} payment_id: #{@payment_id}, client_retraction_ref:"\
      " #{@client_retraction_ref}, memo: #{@memo}, note: #{@note}, acceptance_mode:"\
      " #{@acceptance_mode}, transfer_type: #{@transfer_type}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} payment_id: #{@payment_id.inspect}, client_retraction_ref:"\
      " #{@client_retraction_ref.inspect}, memo: #{@memo.inspect}, note: #{@note.inspect},"\
      " acceptance_mode: #{@acceptance_mode.inspect}, transfer_type: #{@transfer_type.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
