# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Wrapper used by `POST /transfers/search` to address the `transferType:
  # RETRACTION` variant. See [Searching](page:concepts/searching) and
  # [Transfers](page:resources/transfers).
  class PaymentRetractionSearch < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Discriminator value identifying this as a payment quote.
    # @return [TransferType16]
    attr_accessor :transfer_type

    # Filter criteria. Multiple filters are ANDed together.
    # @return [Array[PaymentRetractionSearchFilterItem]]
    attr_accessor :filters

    # Sort criteria. Applied in order. If omitted, the endpoint's default sort
    # is used.
    # @return [Array[PaymentRetractionSearchSortItem]]
    attr_accessor :sort

    # Page number (1-based). Defaults to 1.
    # @return [Integer]
    attr_accessor :page

    # Number of results per page. Defaults to the endpoint's limit.
    # @return [Integer]
    attr_accessor :page_size

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['transfer_type'] = 'transferType'
      @_hash['filters'] = 'filters'
      @_hash['sort'] = 'sort'
      @_hash['page'] = 'page'
      @_hash['page_size'] = 'pageSize'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(transfer_type:, filters:, sort:, page:, page_size:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @transfer_type = transfer_type
      @filters = filters
      @sort = sort
      @page = page
      @page_size = page_size
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      transfer_type = hash.key?('transferType') ? hash['transferType'] : nil
      # Parameter is an array, so we need to iterate through it
      filters = nil
      unless hash['filters'].nil?
        filters = []
        hash['filters'].each do |structure|
          filters << (PaymentRetractionSearchFilterItem.from_hash(structure) if structure)
        end
      end

      filters = nil unless hash.key?('filters')
      # Parameter is an array, so we need to iterate through it
      sort = nil
      unless hash['sort'].nil?
        sort = []
        hash['sort'].each do |structure|
          sort << (PaymentRetractionSearchSortItem.from_hash(structure) if structure)
        end
      end

      sort = nil unless hash.key?('sort')
      page = hash.key?('page') ? hash['page'] : nil
      page_size = hash.key?('pageSize') ? hash['pageSize'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PaymentRetractionSearch.new(transfer_type: transfer_type,
                                  filters: filters,
                                  sort: sort,
                                  page: page,
                                  page_size: page_size,
                                  additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PaymentRetractionSearch | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.transfer_type,
                                ->(val) { TransferType16.validate(val) }) and
            APIHelper.valid_type?(value.filters,
                                  ->(val) { PaymentRetractionSearchFilterItem.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.sort,
                                  ->(val) { PaymentRetractionSearchSortItem.validate(val) },
                                  is_model_hash: true,
                                  is_inner_model_hash: true) and
            APIHelper.valid_type?(value.page,
                                  ->(val) { val.instance_of? Integer }) and
            APIHelper.valid_type?(value.page_size,
                                  ->(val) { val.instance_of? Integer })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['transferType'],
                              ->(val) { TransferType16.validate(val) }) and
          APIHelper.valid_type?(value['filters'],
                                ->(val) { PaymentRetractionSearchFilterItem.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['sort'],
                                ->(val) { PaymentRetractionSearchSortItem.validate(val) },
                                is_model_hash: true,
                                is_inner_model_hash: true) and
          APIHelper.valid_type?(value['page'],
                                ->(val) { val.instance_of? Integer }) and
          APIHelper.valid_type?(value['pageSize'],
                                ->(val) { val.instance_of? Integer })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} transfer_type: #{@transfer_type}, filters: #{@filters}, sort: #{@sort},"\
      " page: #{@page}, page_size: #{@page_size}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} transfer_type: #{@transfer_type.inspect}, filters: #{@filters.inspect},"\
      " sort: #{@sort.inspect}, page: #{@page.inspect}, page_size: #{@page_size.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
