# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module PqApiV2
  # A [Payment Job](page:resources/payment-jobs) — a CSV-driven batch of
  # payments processed asynchronously — returned with HATEOAS navigation links.
  # Track progress via the `JOBS.UPDATED` webhook namespaces. See [Payment
  # Jobs](page:resources/payment-jobs).
  class PaymentJobObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :token

    # Reference ID in the PayQuicker Hosted Portal, if applicable.
    # @return [String]
    attr_accessor :portal_id

    # The name given to a computer file in order to distinguish it from other
    # files
    # @return [String]
    attr_accessor :filename

    # Date and time when the resource was created. ISO 8601 format.
    # @return [DateTime]
    attr_accessor :created_at

    # Transfer is scheduled and will not process before this time. ISO 8601
    # format.
    # @return [DateTime]
    attr_accessor :not_before

    # Total number of records in the job file
    # @return [Integer]
    attr_accessor :total_count

    # Number of valid/processable records
    # @return [Integer]
    attr_accessor :valid_count

    # Number of invalid/unprocessable records
    # @return [Integer]
    attr_accessor :invalid_count

    # Kind of batch job — `PAYMENTS` for [Payment
    # Jobs](page:resources/payment-jobs) (CSV-driven batches that produce
    # payment quotes) or `INVITATIONS` for [Invitation
    # Jobs](page:resources/invitation-jobs) (CSV-driven batches that produce
    # invitations). Determines the shape of the produced items.
    # @return [String]
    attr_accessor :type

    # Lifecycle status of a [Payment Job](page:resources/payment-jobs) or
    # [Invitation Job](page:resources/invitation-jobs) — values include
    # `CREATED`, `IN_PROGRESS`, `COMPLETED`, `FAILED`, and `CANCELLED`.
    # Subscribe to the job's `*JOBS.UPDATED` / `*JOBS.COMPLETED` /
    # `*JOBS.FAILED` webhook namespaces for status change notifications.
    # @return [String]
    attr_accessor :status

    # A map of navigation links related to the current resource, classified by
    # their relationship to the current resource following RFC 8288 / HAL best
    # practices.
    # @return [Hash[String, NavigationLink]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['portal_id'] = 'portalId'
      @_hash['filename'] = 'filename'
      @_hash['created_at'] = 'createdAt'
      @_hash['not_before'] = 'notBefore'
      @_hash['total_count'] = 'totalCount'
      @_hash['valid_count'] = 'validCount'
      @_hash['invalid_count'] = 'invalidCount'
      @_hash['type'] = 'type'
      @_hash['status'] = 'status'
      @_hash['links'] = '_links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        not_before
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(token:, portal_id:, filename:, created_at:, total_count:,
                   valid_count:, invalid_count:, type:, status:, links:,
                   not_before: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @token = token
      @portal_id = portal_id
      @filename = filename
      @created_at = created_at
      @not_before = not_before unless not_before == SKIP
      @total_count = total_count
      @valid_count = valid_count
      @invalid_count = invalid_count
      @type = type
      @status = status
      @links = links
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : nil
      portal_id = hash.key?('portalId') ? hash['portalId'] : nil
      filename = hash.key?('filename') ? hash['filename'] : nil
      created_at = if hash.key?('createdAt')
                     (DateTimeHelper.from_rfc3339(hash['createdAt']) if hash['createdAt'])
                   end
      total_count = hash.key?('totalCount') ? hash['totalCount'] : nil
      valid_count = hash.key?('validCount') ? hash['validCount'] : nil
      invalid_count = hash.key?('invalidCount') ? hash['invalidCount'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      status = hash.key?('status') ? hash['status'] : nil
      links = NavigationLink.from_hash(hash['_links']) if hash['_links']

      links = nil unless hash.key?('_links')
      not_before = if hash.key?('notBefore')
                     (DateTimeHelper.from_rfc3339(hash['notBefore']) if hash['notBefore'])
                   else
                     SKIP
                   end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PaymentJobObject.new(token: token,
                           portal_id: portal_id,
                           filename: filename,
                           created_at: created_at,
                           total_count: total_count,
                           valid_count: valid_count,
                           invalid_count: invalid_count,
                           type: type,
                           status: status,
                           links: links,
                           not_before: not_before,
                           additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    def to_custom_not_before
      DateTimeHelper.to_rfc3339(not_before)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, portal_id: #{@portal_id}, filename: #{@filename},"\
      " created_at: #{@created_at}, not_before: #{@not_before}, total_count: #{@total_count},"\
      " valid_count: #{@valid_count}, invalid_count: #{@invalid_count}, type: #{@type}, status:"\
      " #{@status}, links: #{@links}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, portal_id: #{@portal_id.inspect}, filename:"\
      " #{@filename.inspect}, created_at: #{@created_at.inspect}, not_before:"\
      " #{@not_before.inspect}, total_count: #{@total_count.inspect}, valid_count:"\
      " #{@valid_count.inspect}, invalid_count: #{@invalid_count.inspect}, type: #{@type.inspect},"\
      " status: #{@status.inspect}, links: #{@links.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
