# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module PqApiV2
  # Payment quote — a payer-to-payee disbursement created via `POST /transfers`
  # with `transferType: PAYMENT`. Token prefix `pmnt-`. Follows the standard
  # quote / accept lifecycle: creation returns the quote in
  # `PENDING_ACCEPTANCE`; a separate `POST /transfers/{token}/accept` (or
  # `acceptanceMode: AUTO_ACCEPT` on creation) executes it. See
  # [Transfers](page:resources/transfers).
  class PaymentBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :token

    # Reference ID in the PayQuicker Hosted Portal, if applicable.
    # @return [String]
    attr_accessor :portal_id

    # Allocated money to be sent in the transaction, represented as a string to
    # preserve decimal precision. On transfer-quote responses this value is
    # **always non-negative**, regardless of transfer direction. ([learn
    # more](page:concepts/monetary-precision#quote-responses-are-always-non-nega
    # tive))
    # @return [String]
    attr_accessor :amount

    # Combination of the amount and currency type
    # @return [String]
    attr_accessor :formatted_amount

    # How a transfer quote is processed after creation — required on every
    # transfer quote body. `AUTO_ACCEPT` causes the quote to be accepted and
    # executed in a single call — a fire-and-forget disbursement.
    # `MANUAL_ACCEPT` leaves the quote in `PENDING_ACCEPTANCE` and requires an
    # explicit `POST /transfers/{token}/accept` to execute it. See
    # [Transfers](page:resources/transfers) for the quote / accept lifecycle.
    # @return [String]
    attr_accessor :acceptance_mode

    # Unique value provided by the client for the payment, utilized for
    # reference and deduplication. See [Transfers](page:resources/transfers) for
    # the unified transfers endpoint that handles payments.
    # @return [String]
    attr_accessor :client_payment_ref

    # Date and time when the resource was created. ISO 8601 format.
    # @return [DateTime]
    attr_accessor :created_at

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # Token identifying the destination of funds — a bank-account or
    # electronic-wallet [Instrument](page:resources/instruments), or a [Prepaid
    # Card](page:resources/prepaid-cards). Prefix `dest-`.
    # @return [String]
    attr_accessor :destination_token

    # Program-assigned identifier for the user. Used by Hosted Portal programs
    # (with `email`) to address payees in transactional and search bodies. See
    # [Scope Discriminator](page:concepts/scope-discriminator).
    # @return [String]
    attr_accessor :program_user_id

    # Contact email address for the user account.
    # @return [String]
    attr_accessor :email

    # Optional internal memo, not visible to the user.
    # @return [String]
    attr_accessor :memo

    # Optional comments visible to the user.
    # @return [String]
    attr_accessor :note

    # Purpose tag attached to a payment quote. Used by the platform for
    # reporting categorization and, where the program enables it, by the
    # tax-services calculation pipeline. The value is recorded on the resulting
    # [receipt](page:resources/receipts) and surfaces on statements. See
    # [Transfers](page:resources/transfers) for how purpose flows through the
    # quote / accept lifecycle.
    # @return [String]
    attr_accessor :purpose

    # Token identifying the source of funds — typically a user-wallet token
    # (`user-`), a company funding-account token (`acct-`), or a prepaid-card
    # destination token (`dest-`).
    # @return [String]
    attr_accessor :source_token

    # Lifecycle status of the quote itself (e.g., PENDING_ACCEPTANCE, ACCEPTED,
    # CANCELLED). This reflects whether the quote has been accepted, cancelled,
    # or is still pending — not the status of the resulting transaction. See
    # [Quote Status Types](page:additional-api-information/quote-status-types)
    # for details.
    # @return [String]
    attr_accessor :quote_status

    # Status of the underlying receipt (transaction) that was created when this
    # quote was accepted. This field is only populated after the quote has been
    # accepted and a receipt exists. When the quote is still pending or has been
    # cancelled, this field is null. See [Receipt Status
    # Types](page:additional-api-information/receipt-status-types) for the full
    # list of possible values.
    # @return [String]
    attr_accessor :receipt_status

    # Auto-generated unique identifier representing a receipt, prefixed with
    # `rcpt-`.
    # @return [String]
    attr_accessor :receipt_token

    # Transfer is scheduled and will not process before this time. ISO 8601
    # format.
    # @return [DateTime]
    attr_accessor :not_before

    # Transfer expires if not accepted prior to this time. ISO 8601 format.
    # @return [DateTime]
    attr_accessor :not_after

    # Discriminator value identifying this as a payment quote.
    # @return [TransferType]
    attr_accessor :transfer_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['portal_id'] = 'portalId'
      @_hash['amount'] = 'amount'
      @_hash['formatted_amount'] = 'formattedAmount'
      @_hash['acceptance_mode'] = 'acceptanceMode'
      @_hash['client_payment_ref'] = 'clientPaymentRef'
      @_hash['created_at'] = 'createdAt'
      @_hash['currency'] = 'currency'
      @_hash['destination_token'] = 'destinationToken'
      @_hash['program_user_id'] = 'programUserId'
      @_hash['email'] = 'email'
      @_hash['memo'] = 'memo'
      @_hash['note'] = 'note'
      @_hash['purpose'] = 'purpose'
      @_hash['source_token'] = 'sourceToken'
      @_hash['quote_status'] = 'quoteStatus'
      @_hash['receipt_status'] = 'receiptStatus'
      @_hash['receipt_token'] = 'receiptToken'
      @_hash['not_before'] = 'notBefore'
      @_hash['not_after'] = 'notAfter'
      @_hash['transfer_type'] = 'transferType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        portal_id
        acceptance_mode
        destination_token
        memo
        note
        purpose
        receipt_status
        receipt_token
        not_before
        not_after
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(
      token:, amount:, formatted_amount:,
      client_payment_ref: 'd4b6f130-1d1c-4ce2-903a-0c1ad128f55e', created_at:,
      currency:, program_user_id:, email:,
      source_token: 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860', quote_status:,
      transfer_type:, portal_id: SKIP, acceptance_mode: SKIP,
      destination_token: 'dest-631b200f-665d-4dbe-bd01-3063c9dec97d',
      memo: SKIP, note: SKIP, purpose: SKIP, receipt_status: SKIP,
      receipt_token: SKIP, not_before: SKIP, not_after: SKIP,
      additional_properties: nil
    )
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @token = token
      @portal_id = portal_id unless portal_id == SKIP
      @amount = amount
      @formatted_amount = formatted_amount
      @acceptance_mode = acceptance_mode unless acceptance_mode == SKIP
      @client_payment_ref = client_payment_ref
      @created_at = created_at
      @currency = currency
      @destination_token = destination_token unless destination_token == SKIP
      @program_user_id = program_user_id
      @email = email
      @memo = memo unless memo == SKIP
      @note = note unless note == SKIP
      @purpose = purpose unless purpose == SKIP
      @source_token = source_token
      @quote_status = quote_status
      @receipt_status = receipt_status unless receipt_status == SKIP
      @receipt_token = receipt_token unless receipt_token == SKIP
      @not_before = not_before unless not_before == SKIP
      @not_after = not_after unless not_after == SKIP
      @transfer_type = transfer_type
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : nil
      amount = hash.key?('amount') ? hash['amount'] : nil
      formatted_amount =
        hash.key?('formattedAmount') ? hash['formattedAmount'] : nil
      client_payment_ref =
        hash['clientPaymentRef'] ||= 'd4b6f130-1d1c-4ce2-903a-0c1ad128f55e'
      created_at = if hash.key?('createdAt')
                     (DateTimeHelper.from_rfc3339(hash['createdAt']) if hash['createdAt'])
                   end
      currency = hash.key?('currency') ? hash['currency'] : nil
      program_user_id = hash.key?('programUserId') ? hash['programUserId'] : nil
      email = hash.key?('email') ? hash['email'] : nil
      source_token =
        hash['sourceToken'] ||= 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860'
      quote_status = hash.key?('quoteStatus') ? hash['quoteStatus'] : nil
      transfer_type = hash.key?('transferType') ? hash['transferType'] : nil
      portal_id = hash.key?('portalId') ? hash['portalId'] : SKIP
      acceptance_mode =
        hash.key?('acceptanceMode') ? hash['acceptanceMode'] : SKIP
      destination_token =
        hash['destinationToken'] ||= 'dest-631b200f-665d-4dbe-bd01-3063c9dec97d'
      memo = hash.key?('memo') ? hash['memo'] : SKIP
      note = hash.key?('note') ? hash['note'] : SKIP
      purpose = hash.key?('purpose') ? hash['purpose'] : SKIP
      receipt_status = hash.key?('receiptStatus') ? hash['receiptStatus'] : SKIP
      receipt_token = hash.key?('receiptToken') ? hash['receiptToken'] : SKIP
      not_before = if hash.key?('notBefore')
                     (DateTimeHelper.from_rfc3339(hash['notBefore']) if hash['notBefore'])
                   else
                     SKIP
                   end
      not_after = if hash.key?('notAfter')
                    (DateTimeHelper.from_rfc3339(hash['notAfter']) if hash['notAfter'])
                  else
                    SKIP
                  end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PaymentBase.new(token: token,
                      amount: amount,
                      formatted_amount: formatted_amount,
                      client_payment_ref: client_payment_ref,
                      created_at: created_at,
                      currency: currency,
                      program_user_id: program_user_id,
                      email: email,
                      source_token: source_token,
                      quote_status: quote_status,
                      transfer_type: transfer_type,
                      portal_id: portal_id,
                      acceptance_mode: acceptance_mode,
                      destination_token: destination_token,
                      memo: memo,
                      note: note,
                      purpose: purpose,
                      receipt_status: receipt_status,
                      receipt_token: receipt_token,
                      not_before: not_before,
                      not_after: not_after,
                      additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    def to_custom_not_before
      DateTimeHelper.to_rfc3339(not_before)
    end

    def to_custom_not_after
      DateTimeHelper.to_rfc3339(not_after)
    end

    # Validates an instance of the object from a given value.
    # @param [PaymentBase | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.token,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.amount,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.formatted_amount,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.client_payment_ref,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.created_at,
                                  ->(val) { val.instance_of? DateTime }) and
            APIHelper.valid_type?(value.currency,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.program_user_id,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.email,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.source_token,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.quote_status,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.transfer_type,
                                  ->(val) { TransferType.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['token'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['amount'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['formattedAmount'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['clientPaymentRef'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['createdAt'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['currency'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['programUserId'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['email'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['sourceToken'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['quoteStatus'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['transferType'],
                                ->(val) { TransferType.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, portal_id: #{@portal_id}, amount: #{@amount},"\
      " formatted_amount: #{@formatted_amount}, acceptance_mode: #{@acceptance_mode},"\
      " client_payment_ref: #{@client_payment_ref}, created_at: #{@created_at}, currency:"\
      " #{@currency}, destination_token: #{@destination_token}, program_user_id:"\
      " #{@program_user_id}, email: #{@email}, memo: #{@memo}, note: #{@note}, purpose:"\
      " #{@purpose}, source_token: #{@source_token}, quote_status: #{@quote_status},"\
      " receipt_status: #{@receipt_status}, receipt_token: #{@receipt_token}, not_before:"\
      " #{@not_before}, not_after: #{@not_after}, transfer_type: #{@transfer_type},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, portal_id: #{@portal_id.inspect}, amount:"\
      " #{@amount.inspect}, formatted_amount: #{@formatted_amount.inspect}, acceptance_mode:"\
      " #{@acceptance_mode.inspect}, client_payment_ref: #{@client_payment_ref.inspect},"\
      " created_at: #{@created_at.inspect}, currency: #{@currency.inspect}, destination_token:"\
      " #{@destination_token.inspect}, program_user_id: #{@program_user_id.inspect}, email:"\
      " #{@email.inspect}, memo: #{@memo.inspect}, note: #{@note.inspect}, purpose:"\
      " #{@purpose.inspect}, source_token: #{@source_token.inspect}, quote_status:"\
      " #{@quote_status.inspect}, receipt_status: #{@receipt_status.inspect}, receipt_token:"\
      " #{@receipt_token.inspect}, not_before: #{@not_before.inspect}, not_after:"\
      " #{@not_after.inspect}, transfer_type: #{@transfer_type.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
