# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # A phone number with type classifier.
  class PhoneNumberObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The phone number.
    # @return [String]
    attr_accessor :number

    # ISO 3166-1 alpha-2 country code (two-letter, e.g., `US`, `GB`, `DE`). Used
    # throughout the PayQuicker API in place of the full country name — for
    # residential / mailing addresses on [Users](page:resources/users), for the
    # registered country of [bank-account](page:resources/instruments) and
    # [electronic-wallet](page:resources/instruments) instruments, and to gate
    # which destinations / methods are available to a payee. See [Country
    # Codes](page:additional-api-information/country-codes) for the supported
    # list.
    # @return [String]
    attr_accessor :country

    # Classifies a phone number on a [User](page:resources/users) profile as
    # `PRIMARY` (the user's primary contact number) or `MOBILE` (a number
    # capable of receiving SMS for verification flows and webhook
    # confirmations).
    # @return [String]
    attr_accessor :number_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['number'] = 'number'
      @_hash['country'] = 'country'
      @_hash['number_type'] = 'numberType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(number:, country:, number_type:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @number = number
      @country = country
      @number_type = number_type
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      number = hash.key?('number') ? hash['number'] : nil
      country = hash.key?('country') ? hash['country'] : nil
      number_type = hash.key?('numberType') ? hash['numberType'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PhoneNumberObject.new(number: number,
                            country: country,
                            number_type: number_type,
                            additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PhoneNumberObject | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.number,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.country,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.number_type,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['number'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['country'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['numberType'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} number: #{@number}, country: #{@country}, number_type: #{@number_type},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} number: #{@number.inspect}, country: #{@country.inspect}, number_type:"\
      " #{@number_type.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
