# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Quote returned by `POST /transfers` with `transferType: SPENDBACK` for a
  # Hosted Portal program — debits the payee for goods or services purchased
  # from the payer. Accept with `POST /transfers/{token}/accept`. See
  # [Transfers](page:resources/transfers) and [Spend
  # Options](page:concepts/spend-options).
  class PortalSpendbackQuote < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token identifying the destination of funds — a bank-account or
    # electronic-wallet [Instrument](page:resources/instruments), or a [Prepaid
    # Card](page:resources/prepaid-cards). Prefix `dest-`.
    # @return [String]
    attr_accessor :destination_token

    # Program-assigned identifier for the user. Used by Hosted Portal programs
    # (with `email`) to address payees in transactional and search bodies. See
    # [Scope Discriminator](page:concepts/scope-discriminator).
    # @return [String]
    attr_accessor :program_user_id

    # Contact email address for the user account.
    # @return [String]
    attr_accessor :email

    # Allocated money to be sent in the transaction, represented as a string to
    # preserve decimal precision. On transfer-quote responses this value is
    # **always non-negative**, regardless of transfer direction. ([learn
    # more](page:concepts/monetary-precision#quote-responses-are-always-non-nega
    # tive))
    # @return [String]
    attr_accessor :amount

    # Unique value provided by the client for the spendback
    # @return [String]
    attr_accessor :client_spendback_ref

    # Optional internal memo, not visible to the user.
    # @return [String]
    attr_accessor :memo

    # Optional comments visible to the user.
    # @return [String]
    attr_accessor :note

    # How a transfer quote is processed after creation — required on every
    # transfer quote body. `AUTO_ACCEPT` causes the quote to be accepted and
    # executed in a single call — a fire-and-forget disbursement.
    # `MANUAL_ACCEPT` leaves the quote in `PENDING_ACCEPTANCE` and requires an
    # explicit `POST /transfers/{token}/accept` to execute it. See
    # [Transfers](page:resources/transfers) for the quote / accept lifecycle.
    # @return [String]
    attr_accessor :acceptance_mode

    # Discriminator value identifying this as a spendback quote.
    # @return [TransferType4]
    attr_accessor :transfer_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['destination_token'] = 'destinationToken'
      @_hash['program_user_id'] = 'programUserId'
      @_hash['email'] = 'email'
      @_hash['amount'] = 'amount'
      @_hash['client_spendback_ref'] = 'clientSpendbackRef'
      @_hash['memo'] = 'memo'
      @_hash['note'] = 'note'
      @_hash['acceptance_mode'] = 'acceptanceMode'
      @_hash['transfer_type'] = 'transferType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        destination_token
        memo
        note
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(
      program_user_id:, email:, amount:, client_spendback_ref:,
      acceptance_mode:, transfer_type:,
      destination_token: 'dest-631b200f-665d-4dbe-bd01-3063c9dec97d',
      memo: SKIP, note: SKIP, additional_properties: nil
    )
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @destination_token = destination_token unless destination_token == SKIP
      @program_user_id = program_user_id
      @email = email
      @amount = amount
      @client_spendback_ref = client_spendback_ref
      @memo = memo unless memo == SKIP
      @note = note unless note == SKIP
      @acceptance_mode = acceptance_mode
      @transfer_type = transfer_type
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      program_user_id = hash.key?('programUserId') ? hash['programUserId'] : nil
      email = hash.key?('email') ? hash['email'] : nil
      amount = hash.key?('amount') ? hash['amount'] : nil
      client_spendback_ref =
        hash.key?('clientSpendbackRef') ? hash['clientSpendbackRef'] : nil
      acceptance_mode =
        hash.key?('acceptanceMode') ? hash['acceptanceMode'] : nil
      transfer_type = hash.key?('transferType') ? hash['transferType'] : nil
      destination_token =
        hash['destinationToken'] ||= 'dest-631b200f-665d-4dbe-bd01-3063c9dec97d'
      memo = hash.key?('memo') ? hash['memo'] : SKIP
      note = hash.key?('note') ? hash['note'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PortalSpendbackQuote.new(program_user_id: program_user_id,
                               email: email,
                               amount: amount,
                               client_spendback_ref: client_spendback_ref,
                               acceptance_mode: acceptance_mode,
                               transfer_type: transfer_type,
                               destination_token: destination_token,
                               memo: memo,
                               note: note,
                               additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PortalSpendbackQuote | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.program_user_id,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.email,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.amount,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.client_spendback_ref,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.acceptance_mode,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.transfer_type,
                                  ->(val) { TransferType4.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['programUserId'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['email'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['amount'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['clientSpendbackRef'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['acceptanceMode'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['transferType'],
                                ->(val) { TransferType4.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} destination_token: #{@destination_token}, program_user_id:"\
      " #{@program_user_id}, email: #{@email}, amount: #{@amount}, client_spendback_ref:"\
      " #{@client_spendback_ref}, memo: #{@memo}, note: #{@note}, acceptance_mode:"\
      " #{@acceptance_mode}, transfer_type: #{@transfer_type}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} destination_token: #{@destination_token.inspect}, program_user_id:"\
      " #{@program_user_id.inspect}, email: #{@email.inspect}, amount: #{@amount.inspect},"\
      " client_spendback_ref: #{@client_spendback_ref.inspect}, memo: #{@memo.inspect}, note:"\
      " #{@note.inspect}, acceptance_mode: #{@acceptance_mode.inspect}, transfer_type:"\
      " #{@transfer_type.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
