# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # `PrepaidCardDataImageBase` returned with HATEOAS navigation links — the form
  # returned by [Sensitive Card
  # Operations](page:resources/sensitive-card-operations) image redemption.
  class PrepaidCardDataImageObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Base64-encoded image of the prepaid card (front or back, depending on the
    # request)
    # @return [String]
    attr_accessor :image

    # Specifies which side of the prepaid card image to retrieve (front or back)
    # @return [String]
    attr_accessor :side

    # Token identifying the source of funds — typically a user-wallet token
    # (`user-`), a company funding-account token (`acct-`), or a prepaid-card
    # destination token (`dest-`).
    # @return [String]
    attr_accessor :source_token

    # Data format indicator
    # @return [Format1]
    attr_accessor :format

    # A map of navigation links related to the current resource, classified by
    # their relationship to the current resource following RFC 8288 / HAL best
    # practices.
    # @return [Hash[String, NavigationLink]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['image'] = 'image'
      @_hash['side'] = 'side'
      @_hash['source_token'] = 'sourceToken'
      @_hash['format'] = 'format'
      @_hash['links'] = '_links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(image:, side:,
                   source_token: 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860',
                   format:, links:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @image = image
      @side = side
      @source_token = source_token
      @format = format
      @links = links
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      image = hash.key?('image') ? hash['image'] : nil
      side = hash.key?('side') ? hash['side'] : nil
      source_token =
        hash['sourceToken'] ||= 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860'
      format = hash.key?('format') ? hash['format'] : nil
      links = NavigationLink.from_hash(hash['_links']) if hash['_links']

      links = nil unless hash.key?('_links')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PrepaidCardDataImageObject.new(image: image,
                                     side: side,
                                     source_token: source_token,
                                     format: format,
                                     links: links,
                                     additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} image: #{@image}, side: #{@side}, source_token: #{@source_token}, format:"\
      " #{@format}, links: #{@links}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} image: #{@image.inspect}, side: #{@side.inspect}, source_token:"\
      " #{@source_token.inspect}, format: #{@format.inspect}, links: #{@links.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
