# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # A single filter row inside a `POST /prepaid-cards/search` request body's
  # `filters` array. The `field` value comes from
  # `PrepaidCardSearchFilterField`; valid `comparison` values depend on the
  # field's data type (see [Filtering &
  # Sorting](page:concepts/filtering-sorting)). See [`Prepaid Card Search
  # Fields`](page:additional-api-information/prepaid-card-search-fields#filter-f
  # ields) for the complete catalog of supported field names.
  class PrepaidCardSearchFilterItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Filterable fields for prepaid card search.
    # @return [String]
    attr_accessor :field

    # Comparison operator for filter expressions.
    # Not all operators are valid for every field — see per-endpoint
    # documentation for operator restrictions.
    # @return [String]
    attr_accessor :comparison

    # The filter value.
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['field'] = 'field'
      @_hash['comparison'] = 'comparison'
      @_hash['value'] = 'value'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(field:, comparison:, value:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @field = field
      @comparison = comparison
      @value = value
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      field = hash.key?('field') ? hash['field'] : nil
      comparison = hash.key?('comparison') ? hash['comparison'] : nil
      value = hash.key?('value') ? hash['value'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PrepaidCardSearchFilterItem.new(field: field,
                                      comparison: comparison,
                                      value: value,
                                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} field: #{@field}, comparison: #{@comparison}, value: #{@value},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} field: #{@field.inspect}, comparison: #{@comparison.inspect}, value:"\
      " #{@value.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
