# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # A single-use server-side token issued for redeeming prepaid-card data (PAN /
  # CVV / expiry) directly in the cardholder's browser. The cardholder's client
  # redeems the token against PayQuicker, so your servers never touch sensitive
  # card data. See [Sensitive Card
  # Operations](page:resources/sensitive-card-operations) and
  # [Tokens](page:additional-api-information/tokens).
  class PrepaidCardDataTokenBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token identifying the source of funds — typically a user-wallet token
    # (`user-`), a company funding-account token (`acct-`), or a prepaid-card
    # destination token (`dest-`).
    # @return [String]
    attr_accessor :source_token

    # A token used to reveal prepaid card information in the form of image data
    # (base64) or JSON.
    # @return [String]
    attr_accessor :operation_token

    # Purpose of a single-use server-side token issued via the [Sensitive Card
    # Operations](page:resources/sensitive-card-operations) flow —
    # `PREPAID_CARD_DATA` (display PAN / CVV / expiry to the cardholder's
    # browser) or `PREPAID_CARD_PIN` (reveal or set the card PIN). The token is
    # redeemed directly by the cardholder's browser against PayQuicker, keeping
    # your servers outside of PCI scope. See
    # [Tokens](page:concepts/working-with-tokens) for the broader
    # identifier-token model.
    # @return [String]
    attr_accessor :purpose

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source_token'] = 'sourceToken'
      @_hash['operation_token'] = 'operationToken'
      @_hash['purpose'] = 'purpose'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(source_token: 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860',
                   operation_token:, purpose:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @source_token = source_token
      @operation_token = operation_token
      @purpose = purpose
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source_token =
        hash['sourceToken'] ||= 'acct-3908ab5a-6ce1-474d-8b80-a63a7b147860'
      operation_token =
        hash.key?('operationToken') ? hash['operationToken'] : nil
      purpose = hash.key?('purpose') ? hash['purpose'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PrepaidCardDataTokenBase.new(source_token: source_token,
                                   operation_token: operation_token,
                                   purpose: purpose,
                                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} source_token: #{@source_token}, operation_token: #{@operation_token},"\
      " purpose: #{@purpose}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} source_token: #{@source_token.inspect}, operation_token:"\
      " #{@operation_token.inspect}, purpose: #{@purpose.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
