# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Program — the top-level configuration for a customer's payouts relationship
  # with PayQuicker. Carries the operating currency, the sponsoring bank, the
  # program type ([Hosted Portal vs API Gateway](page:concepts/program-types)),
  # and the company funding accounts associated with the program. Programs are
  # read-only via the API; they are configured by PayQuicker at onboarding.
  # Token prefix `prog-`. See [Programs](page:resources/programs).
  class ProgramBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Auto-generated unique identifier representing a program, prefixed with
    # prog-
    # @return [String]
    attr_accessor :token

    # ISO 4217 three-letter currency code (e.g. `USD`, `EUR`, `GBP`). See
    # [Currency Codes](page:additional-api-information/currency-codes) for the
    # supported list.
    # @return [String]
    attr_accessor :currency

    # Bank sponsoring the program or associated with a financial instrument.
    # @return [String]
    attr_accessor :bank

    # The type of program - `COMMERCIAL`, `CONSUMER_LOYALTY`,
    # `CONSUMER_DISBURSEMENT` or `CONSUMER_GPR`.
    # @return [String]
    attr_accessor :type

    # Company accounts associated with this program
    # @return [Array[AccountObject]]
    attr_accessor :accounts

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['currency'] = 'currency'
      @_hash['bank'] = 'bank'
      @_hash['type'] = 'type'
      @_hash['accounts'] = 'accounts'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        accounts
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(token:, currency: 'USD', bank:, type:, accounts: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @token = token
      @currency = currency
      @bank = bank
      @type = type
      @accounts = accounts unless accounts == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : nil
      currency = hash['currency'] ||= 'USD'
      bank = hash.key?('bank') ? hash['bank'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      # Parameter is an array, so we need to iterate through it
      accounts = nil
      unless hash['accounts'].nil?
        accounts = []
        hash['accounts'].each do |structure|
          accounts << (AccountObject.from_hash(structure) if structure)
        end
      end

      accounts = SKIP unless hash.key?('accounts')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ProgramBase.new(token: token,
                      currency: currency,
                      bank: bank,
                      type: type,
                      accounts: accounts,
                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, currency: #{@currency}, bank: #{@bank}, type: #{@type},"\
      " accounts: #{@accounts}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, currency: #{@currency.inspect}, bank:"\
      " #{@bank.inspect}, type: #{@type.inspect}, accounts: #{@accounts.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
