# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Request object for replacing a prepaid card
  class ReplaceCardRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Auto-generated unique identifier representing a user, prefixed with
    # `user-`.
    # @return [String]
    attr_accessor :user_token

    # Identifier of the card package that governs the physical artwork,
    # packaging, and shipping for a [prepaid
    # card](page:resources/prepaid-cards). Card packages are configured
    # per-program and assigned at card order; consult your PayQuicker
    # representative for the package identifiers available to your program.
    # @return [String]
    attr_accessor :card_package

    # Reason for [prepaid card](page:resources/prepaid-cards) replacement. See
    # [Card Replacement Reason
    # Types](page:additional-api-information/card-replacement-reason-types) for
    # the full list.
    # @return [String]
    attr_accessor :card_replacement_reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['user_token'] = 'userToken'
      @_hash['card_package'] = 'cardPackage'
      @_hash['card_replacement_reason'] = 'cardReplacementReason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(user_token:, card_package:, card_replacement_reason:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @user_token = user_token
      @card_package = card_package
      @card_replacement_reason = card_replacement_reason
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      user_token = hash.key?('userToken') ? hash['userToken'] : nil
      card_package = hash.key?('cardPackage') ? hash['cardPackage'] : nil
      card_replacement_reason =
        hash.key?('cardReplacementReason') ? hash['cardReplacementReason'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ReplaceCardRequest.new(user_token: user_token,
                             card_package: card_package,
                             card_replacement_reason: card_replacement_reason,
                             additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} user_token: #{@user_token}, card_package: #{@card_package},"\
      " card_replacement_reason: #{@card_replacement_reason}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} user_token: #{@user_token.inspect}, card_package: #{@card_package.inspect},"\
      " card_replacement_reason: #{@card_replacement_reason.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
