# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Common base for all `POST /<resource>/search` request bodies — carries
  # `page`, `pageSize`, and shared scope-discrimination fields. Concrete
  # search-request schemas extend this via `allOf`. See
  # [Searching](page:concepts/searching),
  # [Pagination](page:concepts/pagination), and [Scope
  # Discriminator](page:concepts/scope-discriminator).
  class SearchRequestBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Page number (1-based). Defaults to 1.
    # @return [Integer]
    attr_accessor :page

    # Number of results per page. Defaults to the endpoint's limit.
    # @return [Integer]
    attr_accessor :page_size

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page'] = 'page'
      @_hash['page_size'] = 'pageSize'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(page:, page_size:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @page = page
      @page_size = page_size
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash.key?('page') ? hash['page'] : nil
      page_size = hash.key?('pageSize') ? hash['pageSize'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      SearchRequestBase.new(page: page,
                            page_size: page_size,
                            additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} page: #{@page}, page_size: #{@page_size}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} page: #{@page.inspect}, page_size: #{@page_size.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
