# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Statement — a generated activity report for a user's wallet, prepaid-card
  # balance, or company funding account, covering a bounded date range. Carries
  # the statement file contents (base64-encoded), filename, MIME type, the
  # period (`from` / `to` timestamps), and the owning user / prepaid-card /
  # account tokens. Statements are read-only and are produced by the platform on
  # a configured schedule per program. See
  # [Statements](page:resources/statements).
  class StatementBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Program agreement content
    # @return [String]
    attr_accessor :content_base64

    # The name given to a computer file in order to distinguish it from other
    # files
    # @return [String]
    attr_accessor :filename

    # A label used to identify a type of data. Acts like a file extension on the
    # internet.
    # @return [String]
    attr_accessor :mime_type

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :token

    # Auto-generated unique identifier representing a user, prefixed with
    # `user-`.
    # @return [String]
    attr_accessor :user_token

    # Program-assigned identifier for the user. Used by Hosted Portal programs
    # (with `email`) to address payees in transactional and search bodies. See
    # [Scope Discriminator](page:concepts/scope-discriminator).
    # @return [String]
    attr_accessor :program_user_id

    # Auto-generated unique identifier representing a dest, prefixed with dest-.
    # @return [String]
    attr_accessor :prepaid_card_token

    # Beginning date and time of a prepaid card statement
    # @return [Date]
    attr_accessor :from

    # Ending date and time of a prepaid card statement
    # @return [Date]
    attr_accessor :to

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['content_base64'] = 'contentBase64'
      @_hash['filename'] = 'filename'
      @_hash['mime_type'] = 'mimeType'
      @_hash['token'] = 'token'
      @_hash['user_token'] = 'userToken'
      @_hash['program_user_id'] = 'programUserId'
      @_hash['prepaid_card_token'] = 'prepaidCardToken'
      @_hash['from'] = 'from'
      @_hash['to'] = 'to'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        prepaid_card_token
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(content_base64:, filename:, mime_type:, token:, user_token:,
                   program_user_id:, from:, to:, prepaid_card_token: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @content_base64 = content_base64
      @filename = filename
      @mime_type = mime_type
      @token = token
      @user_token = user_token
      @program_user_id = program_user_id
      @prepaid_card_token = prepaid_card_token unless prepaid_card_token == SKIP
      @from = from
      @to = to
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      content_base64 = hash.key?('contentBase64') ? hash['contentBase64'] : nil
      filename = hash.key?('filename') ? hash['filename'] : nil
      mime_type = hash.key?('mimeType') ? hash['mimeType'] : nil
      token = hash.key?('token') ? hash['token'] : nil
      user_token = hash.key?('userToken') ? hash['userToken'] : nil
      program_user_id = hash.key?('programUserId') ? hash['programUserId'] : nil
      from = hash.key?('from') ? hash['from'] : nil
      to = hash.key?('to') ? hash['to'] : nil
      prepaid_card_token =
        hash.key?('prepaidCardToken') ? hash['prepaidCardToken'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      StatementBase.new(content_base64: content_base64,
                        filename: filename,
                        mime_type: mime_type,
                        token: token,
                        user_token: user_token,
                        program_user_id: program_user_id,
                        from: from,
                        to: to,
                        prepaid_card_token: prepaid_card_token,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} content_base64: #{@content_base64}, filename: #{@filename}, mime_type:"\
      " #{@mime_type}, token: #{@token}, user_token: #{@user_token}, program_user_id:"\
      " #{@program_user_id}, prepaid_card_token: #{@prepaid_card_token}, from: #{@from}, to:"\
      " #{@to}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} content_base64: #{@content_base64.inspect}, filename: #{@filename.inspect},"\
      " mime_type: #{@mime_type.inspect}, token: #{@token.inspect}, user_token:"\
      " #{@user_token.inspect}, program_user_id: #{@program_user_id.inspect}, prepaid_card_token:"\
      " #{@prepaid_card_token.inspect}, from: #{@from.inspect}, to: #{@to.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
