# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Discriminator value identifying this as a payment quote.
  class TransferType15
    TRANSFER_TYPE15 = [
      # TODO: Write general description for SPENDBACK
      SPENDBACK = 'SPENDBACK'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TRANSFER_TYPE15.include?(value)
    end

    def self.from_value(value, default_value = SPENDBACK)
      return default_value if value.nil?

      default_value
    end
  end
end
