# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Discriminator value identifying this as a transfer.
  class TransferType17
    TRANSFER_TYPE17 = [
      # TODO: Write general description for TRANSFER
      TRANSFER = 'TRANSFER'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TRANSFER_TYPE17.include?(value)
    end

    def self.from_value(value, default_value = TRANSFER)
      return default_value if value.nil?

      default_value
    end
  end
end
