# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Discriminator value identifying this as a payment quote.
  class TransferType16
    TRANSFER_TYPE16 = [
      # TODO: Write general description for RETRACTION
      RETRACTION = 'RETRACTION'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TRANSFER_TYPE16.include?(value)
    end

    def self.from_value(value, default_value = RETRACTION)
      return default_value if value.nil?

      default_value
    end
  end
end
