# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # A single (country × document-type) entry returned by `POST
  # /documents/requirements/search` — describes which documents a user from a
  # given country must supply for KYC. See [Documents](page:resources/documents)
  # and [KYC Enums](page:additional-api-information/kyc-enums).
  class UserDocumentRequirementItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Country where the user was born
    # @return [String]
    attr_accessor :country_of_birth

    # Country of the user's nationality
    # @return [String]
    attr_accessor :country_of_nationality

    # Array of document items required for verification
    # @return [Array[UserDocumentRequirementItemDocumentsItems]]
    attr_accessor :documents

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['country_of_birth'] = 'countryOfBirth'
      @_hash['country_of_nationality'] = 'countryOfNationality'
      @_hash['documents'] = 'documents'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        country_of_birth
        country_of_nationality
        documents
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(country_of_birth: SKIP, country_of_nationality: SKIP,
                   documents: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @country_of_birth = country_of_birth unless country_of_birth == SKIP
      @country_of_nationality = country_of_nationality unless country_of_nationality == SKIP
      @documents = documents unless documents == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      country_of_birth =
        hash.key?('countryOfBirth') ? hash['countryOfBirth'] : SKIP
      country_of_nationality =
        hash.key?('countryOfNationality') ? hash['countryOfNationality'] : SKIP
      # Parameter is an array, so we need to iterate through it
      documents = nil
      unless hash['documents'].nil?
        documents = []
        hash['documents'].each do |structure|
          documents << (UserDocumentRequirementItemDocumentsItems.from_hash(structure) if structure)
        end
      end

      documents = SKIP unless hash.key?('documents')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      UserDocumentRequirementItem.new(country_of_birth: country_of_birth,
                                      country_of_nationality: country_of_nationality,
                                      documents: documents,
                                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} country_of_birth: #{@country_of_birth}, country_of_nationality:"\
      " #{@country_of_nationality}, documents: #{@documents}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} country_of_birth: #{@country_of_birth.inspect}, country_of_nationality:"\
      " #{@country_of_nationality.inspect}, documents: #{@documents.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
