# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Discriminator identifying this as a business invitation.
  class UserType1
    USER_TYPE1 = [
      # TODO: Write general description for BUSINESS
      BUSINESS = 'BUSINESS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      USER_TYPE1.include?(value)
    end

    def self.from_value(value, default_value = BUSINESS)
      return default_value if value.nil?

      default_value
    end
  end
end
