# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Discriminator identifying this as an individual invitation.
  class UserType
    USER_TYPE = [
      # TODO: Write general description for INDIVIDUAL
      INDIVIDUAL = 'INDIVIDUAL'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      USER_TYPE.include?(value)
    end

    def self.from_value(value, default_value = INDIVIDUAL)
      return default_value if value.nil?

      default_value
    end
  end
end
