# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # A document item nested inside a `UserDocumentRequirementItem` — includes
  # example images, accepted file formats, and per-field metadata. See
  # [Documents](page:resources/documents).
  class UserDocumentRequirementItemDocumentsItems < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Full path of the URI used for this object
    # @return [String]
    attr_accessor :example_image

    # Additional documents that may be required
    # @return [Array[UserDocReqItemDocsItemsSupplementalDocsItems]]
    attr_accessor :supplemental_documents

    # Metadata fields for the document
    # @return [Array[UserDocReqItemDocsItemsMetadataItems]]
    attr_accessor :metadata

    # Review status of a [Document](page:resources/documents) submitted for KYC
    # or business verification — values progress from `NOT_PROVIDED` →
    # `PROVIDED` → `UNDER_REVIEW` → `APPROVED` or `REJECTED`. See [Document
    # Status Types](page:additional-api-information/document-status-types) for
    # the full list and meaning of each value.
    # @return [String]
    attr_accessor :status

    # Kind of [document](page:resources/documents) being uploaded — for example,
    # government ID, proof of address, business registration. Required document
    # types vary by user country and scenario; discover them via `POST
    # /documents/requirements/search`. See [KYC
    # Enums](page:additional-api-information/kyc-enums) for the full value list.
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['example_image'] = 'exampleImage'
      @_hash['supplemental_documents'] = 'supplementalDocuments'
      @_hash['metadata'] = 'metadata'
      @_hash['status'] = 'status'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        example_image
        supplemental_documents
        metadata
        status
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(example_image: SKIP, supplemental_documents: SKIP,
                   metadata: SKIP, status: SKIP, type: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @example_image = example_image unless example_image == SKIP
      @supplemental_documents = supplemental_documents unless supplemental_documents == SKIP
      @metadata = metadata unless metadata == SKIP
      @status = status unless status == SKIP
      @type = type unless type == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      example_image = hash.key?('exampleImage') ? hash['exampleImage'] : SKIP
      # Parameter is an array, so we need to iterate through it
      supplemental_documents = nil
      unless hash['supplementalDocuments'].nil?
        supplemental_documents = []
        hash['supplementalDocuments'].each do |structure|
          supplemental_documents << (UserDocReqItemDocsItemsSupplementalDocsItems.from_hash(structure) if structure)
        end
      end

      supplemental_documents = SKIP unless hash.key?('supplementalDocuments')
      # Parameter is an array, so we need to iterate through it
      metadata = nil
      unless hash['metadata'].nil?
        metadata = []
        hash['metadata'].each do |structure|
          metadata << (UserDocReqItemDocsItemsMetadataItems.from_hash(structure) if structure)
        end
      end

      metadata = SKIP unless hash.key?('metadata')
      status = hash.key?('status') ? hash['status'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      UserDocumentRequirementItemDocumentsItems.new(example_image: example_image,
                                                    supplemental_documents: supplemental_documents,
                                                    metadata: metadata,
                                                    status: status,
                                                    type: type,
                                                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} example_image: #{@example_image}, supplemental_documents:"\
      " #{@supplemental_documents}, metadata: #{@metadata}, status: #{@status}, type: #{@type},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} example_image: #{@example_image.inspect}, supplemental_documents:"\
      " #{@supplemental_documents.inspect}, metadata: #{@metadata.inspect}, status:"\
      " #{@status.inspect}, type: #{@type.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
