# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module PqApiV2
  # Request object for creating a webhook subscription
  class WebhookRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Namespaced event identifier on a webhook delivery — encodes the resource
    # and lifecycle action in a single dotted token (e.g.,
    # `BANKACCOUNTS.CREATED`, `PAYMENTS.UPDATED.STATUS.COMPLETE`,
    # `USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE`). Client handlers route on
    # this value to dispatch to per-event business logic. See the
    # [Webhooks](page:concepts/available-webhooks) catalog for the full
    # per-program-type matrix and [Event
    # Notifications](page:concepts/working-with-event-notifications) for retry /
    # idempotency semantics.
    # @return [WebhookNamespaces]
    attr_accessor :namespace

    # Full path of the URI used for this object
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['namespace'] = 'namespace'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(namespace:, url:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @namespace = namespace
      @url = url
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      namespace = hash.key?('namespace') ? hash['namespace'] : nil
      url = hash.key?('url') ? hash['url'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WebhookRequest.new(namespace: namespace,
                         url: url,
                         additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} namespace: #{@namespace}, url: #{@url}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} namespace: #{@namespace.inspect}, url: #{@url.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
