# pq_api_v2
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module PqApiV2
  # A single [Webhook Subscription](page:resources/webhook-subscriptions) — the
  # binding between a webhook event namespace and the URL where the platform
  # delivers it, plus the HMAC secret for signature verification. See
  # [Webhooks](page:concepts/available-webhooks) and [Event
  # Notifications](page:concepts/working-with-event-notifications).
  class WebhookSubscriptionBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token representing the resource. Format is `<prefix>-<uuid>` where the
    # prefix indicates the resource type. See
    # [Tokens](page:concepts/working-with-tokens).
    # @return [String]
    attr_accessor :token

    # Date and time when the resource was created. ISO 8601 format.
    # @return [DateTime]
    attr_accessor :created_at

    # Date and time that the object was last updated
    # @return [DateTime]
    attr_accessor :last_updated

    # Full path of the URI used for this object
    # @return [String]
    attr_accessor :url

    # Namespaced event identifier on a webhook delivery — encodes the resource
    # and lifecycle action in a single dotted token (e.g.,
    # `BANKACCOUNTS.CREATED`, `PAYMENTS.UPDATED.STATUS.COMPLETE`,
    # `USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE`). Client handlers route on
    # this value to dispatch to per-event business logic. See the
    # [Webhooks](page:concepts/available-webhooks) catalog for the full
    # per-program-type matrix and [Event
    # Notifications](page:concepts/working-with-event-notifications) for retry /
    # idempotency semantics.
    # @return [WebhookNamespaces]
    attr_accessor :namespace

    # Statuses a webhook subscription can have.
    # @return [String]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['created_at'] = 'createdAt'
      @_hash['last_updated'] = 'lastUpdated'
      @_hash['url'] = 'url'
      @_hash['namespace'] = 'namespace'
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        last_updated
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(token:, created_at:, url:, namespace:, status:,
                   last_updated: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @token = token
      @created_at = created_at
      @last_updated = last_updated unless last_updated == SKIP
      @url = url
      @namespace = namespace
      @status = status
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : nil
      created_at = if hash.key?('createdAt')
                     (DateTimeHelper.from_rfc3339(hash['createdAt']) if hash['createdAt'])
                   end
      url = hash.key?('url') ? hash['url'] : nil
      namespace = hash.key?('namespace') ? hash['namespace'] : nil
      status = hash.key?('status') ? hash['status'] : nil
      last_updated = if hash.key?('lastUpdated')
                       (DateTimeHelper.from_rfc3339(hash['lastUpdated']) if hash['lastUpdated'])
                     else
                       SKIP
                     end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WebhookSubscriptionBase.new(token: token,
                                  created_at: created_at,
                                  url: url,
                                  namespace: namespace,
                                  status: status,
                                  last_updated: last_updated,
                                  additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    def to_custom_last_updated
      DateTimeHelper.to_rfc3339(last_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, created_at: #{@created_at}, last_updated:"\
      " #{@last_updated}, url: #{@url}, namespace: #{@namespace}, status: #{@status},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, created_at: #{@created_at.inspect}, last_updated:"\
      " #{@last_updated.inspect}, url: #{@url.inspect}, namespace: #{@namespace.inspect}, status:"\
      " #{@status.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
